//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Avisos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Avisos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Avisos", typeof(Avisos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condition.
        /// </summary>
        public static string Condicion {
            get {
                return ResourceManager.GetString("Condicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Within range.
        /// </summary>
        public static string Dentro_rango {
            get {
                return ResourceManager.GetString("Dentro_rango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing sensorization alarm.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new sensorization alarm.
        /// </summary>
        public static string Descripcion_creacion {
            get {
                return ResourceManager.GetString("Descripcion_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing sensorization alarm.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing sensorization alarm.
        /// </summary>
        public static string Descripcion_edicion {
            get {
                return ResourceManager.GetString("Descripcion_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensorization alarms stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Different.
        /// </summary>
        public static string Diferente {
            get {
                return ResourceManager.GetString("Diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device.
        /// </summary>
        public static string Dispositivo {
            get {
                return ResourceManager.GetString("Dispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in the devices selected..
        /// </summary>
        public static string Error_sensor {
            get {
                return ResourceManager.GetString("Error_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Out of range.
        /// </summary>
        public static string Fuera_rango {
            get {
                return ResourceManager.GetString("Fuera_rango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equal.
        /// </summary>
        public static string Igual {
            get {
                return ResourceManager.GetString("Igual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the sensors you want to assign from the list on the left and press the button that points to the right to assign them to the alarm..
        /// </summary>
        public static string Info_1 {
            get {
                return ResourceManager.GetString("Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To remove a sensor you must select it in the right list and press the button that points to the left..
        /// </summary>
        public static string Info_2 {
            get {
                return ResourceManager.GetString("Info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If no sensor is selected, the alarm will be assigned to all types and the company selected..
        /// </summary>
        public static string Info_3 {
            get {
                return ResourceManager.GetString("Info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If no sensor is selected, the alarm will be assigned to all types selected..
        /// </summary>
        public static string Info_3_sin_empresa {
            get {
                return ResourceManager.GetString("Info_3_sin_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Greater than.
        /// </summary>
        public static string Mayor_que {
            get {
                return ResourceManager.GetString("Mayor_que", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Smaller than.
        /// </summary>
        public static string Menor_que {
            get {
                return ResourceManager.GetString("Menor_que", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separate the range valors using &quot;;&quot; (Ex: 5.0;9.0)..
        /// </summary>
        public static string Mensaje_rango {
            get {
                return ResourceManager.GetString("Mensaje_rango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value field must be a numeric range..
        /// </summary>
        public static string Rango_numerico {
            get {
                return ResourceManager.GetString("Rango_numerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sensors.
        /// </summary>
        public static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor.
        /// </summary>
        public static string Sensor_simple {
            get {
                return ResourceManager.GetString("Sensor_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assigned sensors.
        /// </summary>
        public static string Sensores_asignados {
            get {
                return ResourceManager.GetString("Sensores_asignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unassigned sensors.
        /// </summary>
        public static string Sensores_sinasignar {
            get {
                return ResourceManager.GetString("Sensores_sinasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accelerometer.
        /// </summary>
        public static string Tipo_Acelerometro {
            get {
                return ResourceManager.GetString("Tipo_Acelerometro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Humidity.
        /// </summary>
        public static string Tipo_Humedad {
            get {
                return ResourceManager.GetString("Tipo_Humedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light.
        /// </summary>
        public static string Tipo_Luz {
            get {
                return ResourceManager.GetString("Tipo_Luz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pressure.
        /// </summary>
        public static string Tipo_Presion {
            get {
                return ResourceManager.GetString("Tipo_Presion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor Type.
        /// </summary>
        public static string Tipo_sensor {
            get {
                return ResourceManager.GetString("Tipo_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature.
        /// </summary>
        public static string Tipo_Temperatura {
            get {
                return ResourceManager.GetString("Tipo_Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value field must be a number..
        /// </summary>
        public static string Valor_numerico {
            get {
                return ResourceManager.GetString("Valor_numerico", resourceCulture);
            }
        }
    }
}
