//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Diagnosis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diagnosis() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Diagnosis", typeof(Diagnosis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Absolute throttle position.
        /// </summary>
        public static string AbsoluteThrottlePosition {
            get {
                return ResourceManager.GetString("AbsoluteThrottlePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Air flow rate from mass air flow sensor.
        /// </summary>
        public static string AirFlowRateFromMassAirFlowSensor {
            get {
                return ResourceManager.GetString("AirFlowRateFromMassAirFlowSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Barometric pressure.
        /// </summary>
        public static string BarometricPressure {
            get {
                return ResourceManager.GetString("BarometricPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculated load value.
        /// </summary>
        public static string CalculatedLoadValue {
            get {
                return ResourceManager.GetString("CalculatedLoadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandedEGR.
        /// </summary>
        public static string CommandedEGR {
            get {
                return ResourceManager.GetString("CommandedEGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control module voltage.
        /// </summary>
        public static string ControlModuleVoltage {
            get {
                return ResourceManager.GetString("ControlModuleVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle diagnostic information.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance travelled since DTCs cleared.
        /// </summary>
        public static string DistanceTravelledSinceDTCsCleared {
            get {
                return ResourceManager.GetString("DistanceTravelledSinceDTCsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance travelled while MILIs active.
        /// </summary>
        public static string DistanceTravelledWhileMILIsActivated {
            get {
                return ResourceManager.GetString("DistanceTravelledWhileMILIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EGRError.
        /// </summary>
        public static string EGRError {
            get {
                return ResourceManager.GetString("EGRError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engine coolant temperature.
        /// </summary>
        public static string EngineCoolantTemperature {
            get {
                return ResourceManager.GetString("EngineCoolantTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engine RPM.
        /// </summary>
        public static string EngineRPM {
            get {
                return ResourceManager.GetString("EngineRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected {0} has not the diagnosis module..
        /// </summary>
        public static string Error_modulo {
            get {
                return ResourceManager.GetString("Error_modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select at least one value.
        /// </summary>
        public static string Error_valores_seleccionados {
            get {
                return ResourceManager.GetString("Error_valores_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuel consumption.
        /// </summary>
        public static string FuelConsumption {
            get {
                return ResourceManager.GetString("FuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuel rail pressure.
        /// </summary>
        public static string FuelRailPressure {
            get {
                return ResourceManager.GetString("FuelRailPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignition timing advance for first cylinder.
        /// </summary>
        public static string IgnitionTimingAdvanceFor1Cylinder {
            get {
                return ResourceManager.GetString("IgnitionTimingAdvanceFor1Cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intake air temperature.
        /// </summary>
        public static string IntakeAirTemperature {
            get {
                return ResourceManager.GetString("IntakeAirTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intake manifold absolute pressure.
        /// </summary>
        public static string IntakeManifoldAbsolutePressure {
            get {
                return ResourceManager.GetString("IntakeManifoldAbsolutePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No options selected.
        /// </summary>
        public static string Ninguna_opcion_seleccionada {
            get {
                return ResourceManager.GetString("Ninguna_opcion_seleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of warm ups since DTCs cleared.
        /// </summary>
        public static string NumberOfWarmUpsSinceDTCsCleared {
            get {
                return ResourceManager.GetString("NumberOfWarmUpsSinceDTCsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} options selected.
        /// </summary>
        public static string Opciones_seleccionadas {
            get {
                return ResourceManager.GetString("Opciones_seleccionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relative throttle position.
        /// </summary>
        public static string RelativeThrottlePosition {
            get {
                return ResourceManager.GetString("RelativeThrottlePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no records for the selected vehicle between the indicated dates..
        /// </summary>
        public static string Sin_registros {
            get {
                return ResourceManager.GetString("Sin_registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time since engine starts.
        /// </summary>
        public static string TimeSinceEngineStarts {
            get {
                return ResourceManager.GetString("TimeSinceEngineStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Values.
        /// </summary>
        public static string Valores_diagnosis {
            get {
                return ResourceManager.GetString("Valores_diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle speed.
        /// </summary>
        public static string VehicleSpeed {
            get {
                return ResourceManager.GetString("VehicleSpeed", resourceCulture);
            }
        }
    }
}
