//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Equipos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Equipos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Equipos", typeof(Equipos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Devices.
        /// </summary>
        public static string Anadir_equipos {
            get {
                return ResourceManager.GetString("Anadir_equipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatic.
        /// </summary>
        public static string Automatico {
            get {
                return ResourceManager.GetString("Automatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baud Rate.
        /// </summary>
        public static string Baud_rate {
            get {
                return ResourceManager.GetString("Baud_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check In.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check In / Out.
        /// </summary>
        public static string CheckInOut {
            get {
                return ResourceManager.GetString("CheckInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check In.
        /// </summary>
        public static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check In / Out.
        /// </summary>
        public static string CIO {
            get {
                return ResourceManager.GetString("CIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Out.
        /// </summary>
        public static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Swarm.
        /// </summary>
        public static string Colmena {
            get {
                return ResourceManager.GetString("Colmena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase.
        /// </summary>
        public static string Compra {
            get {
                return ResourceManager.GetString("Compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string Conectado {
            get {
                return ResourceManager.GetString("Conectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Device.
        /// </summary>
        public static string Crear_equipo {
            get {
                return ResourceManager.GetString("Crear_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discard.
        /// </summary>
        public static string Descarte {
            get {
                return ResourceManager.GetString("Descarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string Desconectado {
            get {
                return ResourceManager.GetString("Desconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing traceability device.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new traceability device.
        /// </summary>
        public static string Descripcion_creacion {
            get {
                return ResourceManager.GetString("Descripcion_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing traceability device.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing traceability device.
        /// </summary>
        public static string Descripcion_edicion {
            get {
                return ResourceManager.GetString("Descripcion_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traceability devices stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Device.
        /// </summary>
        public static string Editar_equipo {
            get {
                return ResourceManager.GetString("Editar_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove from swarm.
        /// </summary>
        public static string Eliminar_colmena {
            get {
                return ResourceManager.GetString("Eliminar_colmena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Device.
        /// </summary>
        public static string Eliminar_equipo {
            get {
                return ResourceManager.GetString("Eliminar_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected traceability device?.
        /// </summary>
        public static string Encabezado_borrado {
            get {
                return ResourceManager.GetString("Encabezado_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new traceability device below.
        /// </summary>
        public static string Encabezado_creacion {
            get {
                return ResourceManager.GetString("Encabezado_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected traceability device is shown below.
        /// </summary>
        public static string Encabezado_detalles {
            get {
                return ResourceManager.GetString("Encabezado_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the traceability device below.
        /// </summary>
        public static string Encabezado_edicion {
            get {
                return ResourceManager.GetString("Encabezado_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devices.
        /// </summary>
        public static string Equipo {
            get {
                return ResourceManager.GetString("Equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The traceability device {0} has not been created..
        /// </summary>
        public static string Equipo_creado_error {
            get {
                return ResourceManager.GetString("Equipo_creado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The traceability device {0} has been successfully created..
        /// </summary>
        public static string Equipo_creado_exito {
            get {
                return ResourceManager.GetString("Equipo_creado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The traceability device {0} has not been edited..
        /// </summary>
        public static string Equipo_editado_error {
            get {
                return ResourceManager.GetString("Equipo_editado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The traceability device {0} has been successfully edited..
        /// </summary>
        public static string Equipo_editado_exito {
            get {
                return ResourceManager.GetString("Equipo_editado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The traceability device {0} has not been deleted..
        /// </summary>
        public static string Equipo_eliminado_error {
            get {
                return ResourceManager.GetString("Equipo_eliminado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The traceability device {0} has been successfully deleted..
        /// </summary>
        public static string Equipo_eliminado_exito {
            get {
                return ResourceManager.GetString("Equipo_eliminado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have to select a model..
        /// </summary>
        public static string Equipo_marca_modelo {
            get {
                return ResourceManager.GetString("Equipo_marca_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is not allowed to delete this traceability device since it has associated operations..
        /// </summary>
        public static string Equipo_operaciones {
            get {
                return ResourceManager.GetString("Equipo_operaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main device.
        /// </summary>
        public static string Equipo_principal {
            get {
                return ResourceManager.GetString("Equipo_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device.
        /// </summary>
        public static string Equipo_simple {
            get {
                return ResourceManager.GetString("Equipo_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Swarm device.
        /// </summary>
        public static string Equipos_colmena {
            get {
                return ResourceManager.GetString("Equipos_colmena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devices per page.
        /// </summary>
        public static string Equipos_pagina {
            get {
                return ResourceManager.GetString("Equipos_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not generate an identifier for the selected model..
        /// </summary>
        public static string Error_identificador_modelo {
            get {
                return ResourceManager.GetString("Error_identificador_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a traceability device with the IMEI {0}..
        /// </summary>
        public static string Error_IMEI_repetido {
            get {
                return ResourceManager.GetString("Error_IMEI_repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only {0} models can use photocell..
        /// </summary>
        public static string Error_modelo_fotocelula {
            get {
                return ResourceManager.GetString("Error_modelo_fotocelula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Before creating a traceability device there must exist a device type to be able to assign it. Enter the name of the device type you want to create and try again..
        /// </summary>
        public static string Falta_tipo_equipo {
            get {
                return ResourceManager.GetString("Falta_tipo_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter by operation type.
        /// </summary>
        public static string Filtrar_tipo_operacion {
            get {
                return ResourceManager.GetString("Filtrar_tipo_operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identifier.
        /// </summary>
        public static string Identificador {
            get {
                return ResourceManager.GetString("Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The entered identifier is already in use..
        /// </summary>
        public static string Identificador_repetido {
            get {
                return ResourceManager.GetString("Identificador_repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory.
        /// </summary>
        public static string Inventario {
            get {
                return ResourceManager.GetString("Inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For Android devices insert the IMEI. For handheld devices insert the MAC address..
        /// </summary>
        public static string Leyenda_equipos_no_fijos {
            get {
                return ResourceManager.GetString("Leyenda_equipos_no_fijos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        public static string Modelo {
            get {
                return ResourceManager.GetString("Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company has not been selected..
        /// </summary>
        public static string No_empresa {
            get {
                return ResourceManager.GetString("No_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not any traceability devices..
        /// </summary>
        public static string No_hay_equipos {
            get {
                return ResourceManager.GetString("No_hay_equipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The operation type has not been selected..
        /// </summary>
        public static string No_tipo_operativa {
            get {
                return ResourceManager.GetString("No_tipo_operativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The location has not been selected..
        /// </summary>
        public static string No_ubicacion {
            get {
                return ResourceManager.GetString("No_ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device.
        /// </summary>
        public static string Nombre_equipo {
            get {
                return ResourceManager.GetString("Nombre_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IP address.
        /// </summary>
        public static string Nombre_IP {
            get {
                return ResourceManager.GetString("Nombre_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAC address.
        /// </summary>
        public static string Nombre_MAC {
            get {
                return ResourceManager.GetString("Nombre_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Port.
        /// </summary>
        public static string Nombre_puerto {
            get {
                return ResourceManager.GetString("Nombre_puerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial Port.
        /// </summary>
        public static string Nombre_puerto_serie {
            get {
                return ResourceManager.GetString("Nombre_puerto_serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devices count.
        /// </summary>
        public static string Numero_equipos {
            get {
                return ResourceManager.GetString("Numero_equipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation.
        /// </summary>
        public static string Operacion {
            get {
                return ResourceManager.GetString("Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provision.
        /// </summary>
        public static string Provision {
            get {
                return ResourceManager.GetString("Provision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When selecting the provision operation for a new traceability device you must also select which product should be provisioned..
        /// </summary>
        public static string Provision_sin_tipo {
            get {
                return ResourceManager.GetString("Provision_sin_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theft.
        /// </summary>
        public static string Robo {
            get {
                return ResourceManager.GetString("Robo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracing.
        /// </summary>
        public static string Seguimiento {
            get {
                return ResourceManager.GetString("Seguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution time [sec].
        /// </summary>
        public static string Segundos_auto {
            get {
                return ResourceManager.GetString("Segundos_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Type.
        /// </summary>
        public static string Tipo_equipo {
            get {
                return ResourceManager.GetString("Tipo_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation type.
        /// </summary>
        public static string Tipo_operacion {
            get {
                return ResourceManager.GetString("Tipo_operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operability.
        /// </summary>
        public static string Tipo_operativa {
            get {
                return ResourceManager.GetString("Tipo_operativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use photocell.
        /// </summary>
        public static string Usa_fotocelula {
            get {
                return ResourceManager.GetString("Usa_fotocelula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use location.
        /// </summary>
        public static string Usa_localizacion {
            get {
                return ResourceManager.GetString("Usa_localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IP address not valid..
        /// </summary>
        public static string Validacion_IP {
            get {
                return ResourceManager.GetString("Validacion_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAC address not valid..
        /// </summary>
        public static string Validacion_MAC {
            get {
                return ResourceManager.GetString("Validacion_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only letters (uppercase and lowercase), numbers, spaces and characters &amp;&apos;- are allowed for the Name.
        /// </summary>
        public static string Validacion_nombre {
            get {
                return ResourceManager.GetString("Validacion_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Port Number must be between 1024 and 65536..
        /// </summary>
        public static string Validacion_puerto {
            get {
                return ResourceManager.GetString("Validacion_puerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sale.
        /// </summary>
        public static string Venta {
            get {
                return ResourceManager.GetString("Venta", resourceCulture);
            }
        }
    }
}
