//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Errores", typeof(Errores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The queried asset has not been found in the system (it is not provisioned)..
        /// </summary>
        public static string Activo_no_provisionado {
            get {
                return ResourceManager.GetString("Activo_no_provisionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company only allows the provision of one asset per product.
        /// </summary>
        public static string Activo_por_producto {
            get {
                return ResourceManager.GetString("Activo_por_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The asset consulted is provisioned as secondary.
        /// </summary>
        public static string Activo_provisionado_secundario {
            get {
                return ResourceManager.GetString("Activo_provisionado_secundario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assets.
        /// </summary>
        public static string Activos {
            get {
                return ResourceManager.GetString("Activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a theft alarm defined on the location..
        /// </summary>
        public static string Alarma_robo_repetida {
            get {
                return ResourceManager.GetString("Alarma_robo_repetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a minimum stock alarm defined on the location for this product..
        /// </summary>
        public static string Alarma_stock_repetida {
            get {
                return ResourceManager.GetString("Alarma_stock_repetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alarms.
        /// </summary>
        public static string Alarmas {
            get {
                return ResourceManager.GetString("Alarmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories.
        /// </summary>
        public static string CategoriasActivos {
            get {
                return ResourceManager.GetString("CategoriasActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} queried does not exist in the system..
        /// </summary>
        public static string Consulta_no_existe {
            get {
                return ResourceManager.GetString("Consulta_no_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The address is a main office, the company or entity to which it belongs will lose its main office..
        /// </summary>
        public static string Direcciones_sede_principal {
            get {
                return ResourceManager.GetString("Direcciones_sede_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User&apos;s company does not match the one received by parameter..
        /// </summary>
        public static string Empresa_no_coincide {
            get {
                return ResourceManager.GetString("Empresa_no_coincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User&apos;s company and the company which the asset is associated with do not match..
        /// </summary>
        public static string Empresa_usuario_distinta_activo {
            get {
                return ResourceManager.GetString("Empresa_usuario_distinta_activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User&apos;s company and the company which the reader is associated with do not match..
        /// </summary>
        public static string Empresa_usuario_distinta_equipo {
            get {
                return ResourceManager.GetString("Empresa_usuario_distinta_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User&apos;s company and the company which the location is associated with do not match..
        /// </summary>
        public static string Empresa_usuario_distinta_localizacion {
            get {
                return ResourceManager.GetString("Empresa_usuario_distinta_localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The asset type selected doesn&apos;t belong to the user company..
        /// </summary>
        public static string Empresa_usuario_distinta_tipo {
            get {
                return ResourceManager.GetString("Empresa_usuario_distinta_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        public static string Empresas {
            get {
                return ResourceManager.GetString("Empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipments.
        /// </summary>
        public static string Equipos {
            get {
                return ResourceManager.GetString("Equipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is required..
        /// </summary>
        public static string Error_campo_requerido {
            get {
                return ResourceManager.GetString("Error_campo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a value less than or equal to {0}..
        /// </summary>
        public static string Error_cantidad_maxima {
            get {
                return ResourceManager.GetString("Error_cantidad_maxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a value greater than or equal to {0}..
        /// </summary>
        public static string Error_cantidad_minima {
            get {
                return ResourceManager.GetString("Error_cantidad_minima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred while checking the zip file..
        /// </summary>
        public static string Error_Comprobacion_Zip {
            get {
                return ResourceManager.GetString("Error_Comprobacion_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is not possible to create {0} without first creating {1}..
        /// </summary>
        public static string Error_dependencias_crear {
            get {
                return ResourceManager.GetString("Error_dependencias_crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It has {0} associated, delete them and try again..
        /// </summary>
        public static string Error_eliminar {
            get {
                return ResourceManager.GetString("Error_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a valid email address..
        /// </summary>
        public static string Error_email_incorrecto {
            get {
                return ResourceManager.GetString("Error_email_incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company id must be a numeric value.
        /// </summary>
        public static string Error_empresa_id_numerico {
            get {
                return ResourceManager.GetString("Error_empresa_id_numerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not create more than one traceability or sensorization companies for a non-distributing entity.
        /// </summary>
        public static string Error_empresa_nodist {
            get {
                return ResourceManager.GetString("Error_empresa_nodist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The entity id must be a numeric value.
        /// </summary>
        public static string Error_entidad_id_numerico {
            get {
                return ResourceManager.GetString("Error_entidad_id_numerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving information..
        /// </summary>
        public static string Error_grabar {
            get {
                return ResourceManager.GetString("Error_grabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {name} image can not exceed the height of {size} px.
        /// </summary>
        public static string Error_imagen_alta {
            get {
                return ResourceManager.GetString("Error_imagen_alta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {name} image can not exceed the width of {size} px.
        /// </summary>
        public static string Error_imagen_ancha {
            get {
                return ResourceManager.GetString("Error_imagen_ancha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {name} image must be at least {size} px tall.
        /// </summary>
        public static string Error_imagen_baja {
            get {
                return ResourceManager.GetString("Error_imagen_baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {name} image must be at least {size} px wide.
        /// </summary>
        public static string Error_imagen_estrecha {
            get {
                return ResourceManager.GetString("Error_imagen_estrecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file &quot;{name}&quot; has not been found or is not valid..
        /// </summary>
        public static string Error_imagen_no_encontrada {
            get {
                return ResourceManager.GetString("Error_imagen_no_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected error..
        /// </summary>
        public static string Error_inesperado {
            get {
                return ResourceManager.GetString("Error_inesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you add a new zip file, you must provide a reference..
        /// </summary>
        public static string Error_Marca_FicheroSinReferencia {
            get {
                return ResourceManager.GetString("Error_Marca_FicheroSinReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is necessary to upload a zip file if you provide a reference..
        /// </summary>
        public static string Error_Marca_ReferenciaSinFichero {
            get {
                return ResourceManager.GetString("Error_Marca_ReferenciaSinFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value of {0} can not be null.
        /// </summary>
        public static string Error_no_nulo_de {
            get {
                return ResourceManager.GetString("Error_no_nulo_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value of {0} can not be null.
        /// </summary>
        public static string Error_no_nulo_del {
            get {
                return ResourceManager.GetString("Error_no_nulo_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} that you try to delete can not be deleted because it has references with {1}.
        /// </summary>
        public static string Error_referencias {
            get {
                return ResourceManager.GetString("Error_referencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} that you try to delete can not be deleted because it has references with {1}.
        /// </summary>
        public static string Error_referencias_fem {
            get {
                return ResourceManager.GetString("Error_referencias_fem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is of type {1}..
        /// </summary>
        public static string Error_tipo_campo {
            get {
                return ResourceManager.GetString("Error_tipo_campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select an user role..
        /// </summary>
        public static string Error_usuario_sin_rol {
            get {
                return ResourceManager.GetString("Error_usuario_sin_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field can not have a negative value..
        /// </summary>
        public static string Error_valor_negativo {
            get {
                return ResourceManager.GetString("Error_valor_negativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The zip file content is not correct. It can only contain a single directory..
        /// </summary>
        public static string Error_Zip_Contenido {
            get {
                return ResourceManager.GetString("Error_Zip_Contenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file {0} already exists. Check the reference and existing versions..
        /// </summary>
        public static string Error_Zip_Existente {
            get {
                return ResourceManager.GetString("Error_Zip_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order Id over the check in is attempted has been indicated but not the order type..
        /// </summary>
        public static string Falta_tipo_orden {
            get {
                return ResourceManager.GetString("Falta_tipo_orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The segment is not associated with the location..
        /// </summary>
        public static string Hueco_no_pertenece_ubicacion {
            get {
                return ResourceManager.GetString("Hueco_no_pertenece_ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The indicated segment is not valid.
        /// </summary>
        public static string Hueco_no_valido {
            get {
                return ResourceManager.GetString("Hueco_no_valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} queried does not exist in the system..
        /// </summary>
        public static string La_consulta_no_existe {
            get {
                return ResourceManager.GetString("La_consulta_no_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The location over the check in is attempted does not correspond to the destination contemplated in the order; you can perform a free check in but not a check in associated with an order. .
        /// </summary>
        public static string Localizacion_diferente_destino {
            get {
                return ResourceManager.GetString("Localizacion_diferente_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locations.
        /// </summary>
        public static string Localizaciones {
            get {
                return ResourceManager.GetString("Localizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No assets were found in the system associated with the indicated location..
        /// </summary>
        public static string No_existen_activos_localizacion {
            get {
                return ResourceManager.GetString("No_existen_activos_localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No secondary assets have been found associated with the asset in question..
        /// </summary>
        public static string No_existen_activos_secundarios {
            get {
                return ResourceManager.GetString("No_existen_activos_secundarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No brands were found in the system..
        /// </summary>
        public static string No_existen_marcas {
            get {
                return ResourceManager.GetString("No_existen_marcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No models were found in the system associated with the indicated brand..
        /// </summary>
        public static string No_existen_modelos {
            get {
                return ResourceManager.GetString("No_existen_modelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No category type selected, please select one..
        /// </summary>
        public static string No_seleccionada_categoria {
            get {
                return ResourceManager.GetString("No_seleccionada_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No company selected, please select one..
        /// </summary>
        public static string No_seleccionada_empresa {
            get {
                return ResourceManager.GetString("No_seleccionada_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No location selected, please select one..
        /// </summary>
        public static string No_seleccionada_ubicacion {
            get {
                return ResourceManager.GetString("No_seleccionada_ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No device selected, please select one..
        /// </summary>
        public static string No_seleccionado_dispositivo {
            get {
                return ResourceManager.GetString("No_seleccionado_dispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No model selected, please select one..
        /// </summary>
        public static string No_seleccionado_modelo {
            get {
                return ResourceManager.GetString("No_seleccionado_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No device type selected, please select one..
        /// </summary>
        public static string No_seleccionado_tipo_equipo {
            get {
                return ResourceManager.GetString("No_seleccionado_tipo_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operations.
        /// </summary>
        public static string Operaciones {
            get {
                return ResourceManager.GetString("Operaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchases.
        /// </summary>
        public static string OrdenesCompra {
            get {
                return ResourceManager.GetString("OrdenesCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfers.
        /// </summary>
        public static string OrdenesTransferencia {
            get {
                return ResourceManager.GetString("OrdenesTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sales.
        /// </summary>
        public static string OrdenesVenta {
            get {
                return ResourceManager.GetString("OrdenesVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The origin of the user could not be validated..
        /// </summary>
        public static string Origen_invalido {
            get {
                return ResourceManager.GetString("Origen_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suppliers.
        /// </summary>
        public static string Proovedores {
            get {
                return ResourceManager.GetString("Proovedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tag code has been received..
        /// </summary>
        public static string Tags_no_recibidos {
            get {
                return ResourceManager.GetString("Tags_no_recibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string TiposActivos {
            get {
                return ResourceManager.GetString("TiposActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Token.
        /// </summary>
        public static string Token_invalido {
            get {
                return ResourceManager.GetString("Token_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The indicated location is not valid.
        /// </summary>
        public static string Ubicacion_no_valida {
            get {
                return ResourceManager.GetString("Ubicacion_no_valida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username or password are not correct..
        /// </summary>
        public static string Usuario_invalido {
            get {
                return ResourceManager.GetString("Usuario_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is no longer in the system.
        /// </summary>
        public static string Usuario_no_existe {
            get {
                return ResourceManager.GetString("Usuario_no_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user does not have access to the module..
        /// </summary>
        public static string Usuario_no_modulo {
            get {
                return ResourceManager.GetString("Usuario_no_modulo", resourceCulture);
            }
        }
    }
}
