//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Flotas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flotas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Flotas", typeof(Flotas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is required..
        /// </summary>
        public static string Campo_vacio {
            get {
                return ResourceManager.GetString("Campo_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Fleet.
        /// </summary>
        public static string Crear_flota {
            get {
                return ResourceManager.GetString("Crear_flota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing fleet.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing fleet.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fleets stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Fleet.
        /// </summary>
        public static string Editar_flota {
            get {
                return ResourceManager.GetString("Editar_flota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected fleet?.
        /// </summary>
        public static string Encabezado_borrado {
            get {
                return ResourceManager.GetString("Encabezado_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new fleet below.
        /// </summary>
        public static string Encabezado_creacion {
            get {
                return ResourceManager.GetString("Encabezado_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected fleet is shown below.
        /// </summary>
        public static string Encabezado_detalles {
            get {
                return ResourceManager.GetString("Encabezado_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the fleet below.
        /// </summary>
        public static string Encabezado_edicion {
            get {
                return ResourceManager.GetString("Encabezado_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fleets.
        /// </summary>
        public static string Flota {
            get {
                return ResourceManager.GetString("Flota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fleet {0} has not been created..
        /// </summary>
        public static string Flota_creada_error {
            get {
                return ResourceManager.GetString("Flota_creada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The flota {0} has been successfully created..
        /// </summary>
        public static string Flota_creada_exito {
            get {
                return ResourceManager.GetString("Flota_creada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fleet {0} has not been edited..
        /// </summary>
        public static string Flota_editada_error {
            get {
                return ResourceManager.GetString("Flota_editada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fleet {0} has been successfully edited..
        /// </summary>
        public static string Flota_editada_exito {
            get {
                return ResourceManager.GetString("Flota_editada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fleet {0} has not been deleted..
        /// </summary>
        public static string Flota_eliminada_error {
            get {
                return ResourceManager.GetString("Flota_eliminada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fleet {0} has been successfully deleted..
        /// </summary>
        public static string Flota_eliminada_exito {
            get {
                return ResourceManager.GetString("Flota_eliminada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A fleet with that name already exists. Please try again..
        /// </summary>
        public static string Flota_existe_nombre {
            get {
                return ResourceManager.GetString("Flota_existe_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fleet.
        /// </summary>
        public static string Flota_simple {
            get {
                return ResourceManager.GetString("Flota_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fleets per page.
        /// </summary>
        public static string Flotas_pagina {
            get {
                return ResourceManager.GetString("Flotas_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
    }
}
