//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Gps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gps() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Gps", typeof(Gps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated at.
        /// </summary>
        public static string Actualizado {
            get {
                return ResourceManager.GetString("Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuel consumption.
        /// </summary>
        public static string Consumo_ruta {
            get {
                return ResourceManager.GetString("Consumo_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route details.
        /// </summary>
        public static string Detalle_ruta {
            get {
                return ResourceManager.GetString("Detalle_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance traveled.
        /// </summary>
        public static string Distancia_ruta {
            get {
                return ResourceManager.GetString("Distancia_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Run.
        /// </summary>
        public static string En_marcha {
            get {
                return ResourceManager.GetString("En_marcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle Activity Status.
        /// </summary>
        public static string Estado_actividad {
            get {
                return ResourceManager.GetString("Estado_actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fleet Status.
        /// </summary>
        public static string Estado_flota {
            get {
                return ResourceManager.GetString("Estado_flota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route end.
        /// </summary>
        public static string Fecha_fin {
            get {
                return ResourceManager.GetString("Fecha_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date.
        /// </summary>
        public static string Fecha_inicio {
            get {
                return ResourceManager.GetString("Fecha_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ago.
        /// </summary>
        public static string Hace {
            get {
                return ResourceManager.GetString("Hace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route Info.
        /// </summary>
        public static string Info_ruta {
            get {
                return ResourceManager.GetString("Info_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route start.
        /// </summary>
        public static string Inicio_ruta {
            get {
                return ResourceManager.GetString("Inicio_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Knots.
        /// </summary>
        public static string Nudos {
            get {
                return ResourceManager.GetString("Nudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Off.
        /// </summary>
        public static string Parado {
            get {
                return ResourceManager.GetString("Parado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinates.
        /// </summary>
        public static string Posicion {
            get {
                return ResourceManager.GetString("Posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current position.
        /// </summary>
        public static string Posicion_actual {
            get {
                return ResourceManager.GetString("Posicion_actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idle.
        /// </summary>
        public static string Ralenti {
            get {
                return ResourceManager.GetString("Ralenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a route.
        /// </summary>
        public static string Recorrido {
            get {
                return ResourceManager.GetString("Recorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary.
        /// </summary>
        public static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Course.
        /// </summary>
        public static string Rumbo {
            get {
                return ResourceManager.GetString("Rumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle Real Time.
        /// </summary>
        public static string Tiempo_real {
            get {
                return ResourceManager.GetString("Tiempo_real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Real time map.
        /// </summary>
        public static string Tiempo_real_descripcion {
            get {
                return ResourceManager.GetString("Tiempo_real_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangulation.
        /// </summary>
        public static string Tiempo_real_loka {
            get {
                return ResourceManager.GetString("Tiempo_real_loka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time spent.
        /// </summary>
        public static string Tiempo_ruta {
            get {
                return ResourceManager.GetString("Tiempo_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show last route.
        /// </summary>
        public static string Ultima_ruta {
            get {
                return ResourceManager.GetString("Ultima_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show last positions.
        /// </summary>
        public static string Ultimas_posiciones {
            get {
                return ResourceManager.GetString("Ultimas_posiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPs speed.
        /// </summary>
        public static string Velocidad_gps {
            get {
                return ResourceManager.GetString("Velocidad_gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Average speed.
        /// </summary>
        public static string Velocidad_ruta {
            get {
                return ResourceManager.GetString("Velocidad_ruta", resourceCulture);
            }
        }
    }
}
