//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idiomas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Idiomas", typeof(Idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GERMAN.
        /// </summary>
        public static string Aleman {
            get {
                return ResourceManager.GetString("Aleman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change to {0}.
        /// </summary>
        public static string Cambiar_a {
            get {
                return ResourceManager.GetString("Cambiar_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is required..
        /// </summary>
        public static string Campo_vacio {
            get {
                return ResourceManager.GetString("Campo_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click to change.
        /// </summary>
        public static string Click_cambiar {
            get {
                return ResourceManager.GetString("Click_cambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Language.
        /// </summary>
        public static string Crear_idioma {
            get {
                return ResourceManager.GetString("Crear_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Culture.
        /// </summary>
        public static string Cultura_idioma {
            get {
                return ResourceManager.GetString("Cultura_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The culture format should be: &quot;xx-YY&quot; (language - country).
        /// </summary>
        public static string Cultura_invalida {
            get {
                return ResourceManager.GetString("Cultura_invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing language.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new language.
        /// </summary>
        public static string Descripcion_creacion {
            get {
                return ResourceManager.GetString("Descripcion_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing language.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing language.
        /// </summary>
        public static string Descripcion_edicion {
            get {
                return ResourceManager.GetString("Descripcion_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languages stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Language.
        /// </summary>
        public static string Editar_idioma {
            get {
                return ResourceManager.GetString("Editar_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Language.
        /// </summary>
        public static string Eliminar_idioma {
            get {
                return ResourceManager.GetString("Eliminar_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected language?.
        /// </summary>
        public static string Encabezado_borrado {
            get {
                return ResourceManager.GetString("Encabezado_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new language below.
        /// </summary>
        public static string Encabezado_creacion {
            get {
                return ResourceManager.GetString("Encabezado_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected language is shown below.
        /// </summary>
        public static string Encabezado_detalles {
            get {
                return ResourceManager.GetString("Encabezado_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the language below.
        /// </summary>
        public static string Encabezado_edicion {
            get {
                return ResourceManager.GetString("Encabezado_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entities.
        /// </summary>
        public static string Entidades {
            get {
                return ResourceManager.GetString("Entidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPANISH.
        /// </summary>
        public static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FRENCH.
        /// </summary>
        public static string Frances {
            get {
                return ResourceManager.GetString("Frances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language icon.
        /// </summary>
        public static string Icono_idioma {
            get {
                return ResourceManager.GetString("Icono_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language icon must have a size of 24x24 px and one of the following formats: &quot;gif, jpg, jpeg, png&quot; .
        /// </summary>
        public static string Icono_idioma_invalido {
            get {
                return ResourceManager.GetString("Icono_idioma_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languages.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language {0} has not been created..
        /// </summary>
        public static string Idioma_creado_error {
            get {
                return ResourceManager.GetString("Idioma_creado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language {0} has been successfully created..
        /// </summary>
        public static string Idioma_creado_exito {
            get {
                return ResourceManager.GetString("Idioma_creado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language {0} has not been edited..
        /// </summary>
        public static string Idioma_editado_error {
            get {
                return ResourceManager.GetString("Idioma_editado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language {0} has been successfully edited..
        /// </summary>
        public static string Idioma_editado_exito {
            get {
                return ResourceManager.GetString("Idioma_editado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language {0} has not been deleted..
        /// </summary>
        public static string Idioma_eliminado_error {
            get {
                return ResourceManager.GetString("Idioma_eliminado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language {0} has been successfully deleted..
        /// </summary>
        public static string Idioma_eliminado_exito {
            get {
                return ResourceManager.GetString("Idioma_eliminado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language {0} is in use by the {1}. Can not be deleted..
        /// </summary>
        public static string Idioma_Referencias {
            get {
                return ResourceManager.GetString("Idioma_Referencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Idioma_simple {
            get {
                return ResourceManager.GetString("Idioma_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languages per page:.
        /// </summary>
        public static string Idiomas_pagina {
            get {
                return ResourceManager.GetString("Idiomas_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENGLISH.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ITALIAN.
        /// </summary>
        public static string Italiano {
            get {
                return ResourceManager.GetString("Italiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language name.
        /// </summary>
        public static string Nombre_idioma {
            get {
                return ResourceManager.GetString("Nombre_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
    }
}
