//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Marcas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Marcas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Marcas", typeof(Marcas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Brand.
        /// </summary>
        public static string Crear_marca {
            get {
                return ResourceManager.GetString("Crear_marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing brand.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing brand.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brands stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Brand.
        /// </summary>
        public static string Editar_marca {
            get {
                return ResourceManager.GetString("Editar_marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Brand.
        /// </summary>
        public static string Eliminar_marca {
            get {
                return ResourceManager.GetString("Eliminar_marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected brand?.
        /// </summary>
        public static string Encabezado_borrado {
            get {
                return ResourceManager.GetString("Encabezado_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new brand below.
        /// </summary>
        public static string Encabezado_creacion {
            get {
                return ResourceManager.GetString("Encabezado_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected brand is shown below.
        /// </summary>
        public static string Encabezado_detalles {
            get {
                return ResourceManager.GetString("Encabezado_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the brand below.
        /// </summary>
        public static string Encabezado_edicion {
            get {
                return ResourceManager.GetString("Encabezado_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand {0} has associated models. You can not remove it..
        /// </summary>
        public static string Error_marca_modelos {
            get {
                return ResourceManager.GetString("Error_marca_modelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip File.
        /// </summary>
        public static string Fichero {
            get {
                return ResourceManager.GetString("Fichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * If the reference of the brand is established, you must necessarily provide a new zip file and vice versa, which will increase the brand&apos;s version. On the other hand if you delete the reference and do not provide any zip file, the reference, version and file of the brand will be set as null..
        /// </summary>
        public static string Informacion_referencia_fichero {
            get {
                return ResourceManager.GetString("Informacion_referencia_fichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brands.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand {0} has not been created..
        /// </summary>
        public static string Marca_creada_error {
            get {
                return ResourceManager.GetString("Marca_creada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand {0} has been successfully created..
        /// </summary>
        public static string Marca_creada_exito {
            get {
                return ResourceManager.GetString("Marca_creada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand {0} has not been edited..
        /// </summary>
        public static string Marca_editada_error {
            get {
                return ResourceManager.GetString("Marca_editada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand {0} has been successfully edited..
        /// </summary>
        public static string Marca_editada_exito {
            get {
                return ResourceManager.GetString("Marca_editada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand {0} has not been deleted..
        /// </summary>
        public static string Marca_eliminada_error {
            get {
                return ResourceManager.GetString("Marca_eliminada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand {0} has been successfully deleted..
        /// </summary>
        public static string Marca_eliminada_exito {
            get {
                return ResourceManager.GetString("Marca_eliminada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        public static string Marca_simple {
            get {
                return ResourceManager.GetString("Marca_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brands per page:.
        /// </summary>
        public static string Marcas_pagina {
            get {
                return ResourceManager.GetString("Marcas_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand&apos;s name is already in use..
        /// </summary>
        public static string Nombre_repetido {
            get {
                return ResourceManager.GetString("Nombre_repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference not found.
        /// </summary>
        public static string Referencia_no_encontrada {
            get {
                return ResourceManager.GetString("Referencia_no_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The brand&apos;s reference is already in use..
        /// </summary>
        public static string Referencia_repetida {
            get {
                return ResourceManager.GetString("Referencia_repetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only letters (uppercase and lowercase) are allowed for the Reference.
        /// </summary>
        public static string Validacion_referencia {
            get {
                return ResourceManager.GetString("Validacion_referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
