//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string Abrir {
            get {
                return ResourceManager.GetString("Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open padlock.
        /// </summary>
        public static string Abrir_candado {
            get {
                return ResourceManager.GetString("Abrir_candado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOGIN.
        /// </summary>
        public static string Acceder {
            get {
                return ResourceManager.GetString("Acceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actions.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADMINISTRATION.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign the selected {0}..
        /// </summary>
        public static string Asignar_seleccionados {
            get {
                return ResourceManager.GetString("Asignar_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign all.
        /// </summary>
        public static string Asignar_todos {
            get {
                return ResourceManager.GetString("Asignar_todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning!.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to.
        /// </summary>
        public static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locked.
        /// </summary>
        public static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to lock the entity?.
        /// </summary>
        public static string Bloquear_entidad {
            get {
                return ResourceManager.GetString("Bloquear_entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to lock the user?.
        /// </summary>
        public static string Bloquear_usuario {
            get {
                return ResourceManager.GetString("Bloquear_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Real-time HD Camera.
        /// </summary>
        public static string Camara_alta_definicion {
            get {
                return ResourceManager.GetString("Camara_alta_definicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes have been made. Are you sure you want to continue?.
        /// </summary>
        public static string Cambios_realizados {
            get {
                return ResourceManager.GetString("Cambios_realizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field is required.
        /// </summary>
        public static string Campo_requerido {
            get {
                return ResourceManager.GetString("Campo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading ....
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid code..
        /// </summary>
        public static string Codigo_no_valido {
            get {
                return ResourceManager.GetString("Codigo_no_valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter verification code.
        /// </summary>
        public static string Codigo_verificacion {
            get {
                return ResourceManager.GetString("Codigo_verificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check the email to reset the password..
        /// </summary>
        public static string Comprobar_correo {
            get {
                return ResourceManager.GetString("Comprobar_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password confirmation.
        /// </summary>
        public static string Confirmacion_pass_olvidada {
            get {
                return ResourceManager.GetString("Confirmacion_pass_olvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset confirmation.
        /// </summary>
        public static string Confirmacion_restablecer_pass {
            get {
                return ResourceManager.GetString("Confirmacion_restablecer_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm email.
        /// </summary>
        public static string Confirmar_email {
            get {
                return ResourceManager.GetString("Confirmar_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created by.
        /// </summary>
        public static string Creada_por {
            get {
                return ResourceManager.GetString("Creada_por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account has been locked, please try again later..
        /// </summary>
        public static string Cuenta_bloqueada {
            get {
                return ResourceManager.GetString("Cuenta_bloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All rights reserved..
        /// </summary>
        public static string Derechos_Reservados {
            get {
                return ResourceManager.GetString("Derechos_Reservados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to unlock the entity?.
        /// </summary>
        public static string Desbloquear_entidad {
            get {
                return ResourceManager.GetString("Desbloquear_entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to unlock the user?.
        /// </summary>
        public static string Desbloquear_usuario {
            get {
                return ResourceManager.GetString("Desbloquear_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The final date ends at 23:59 of the selected day..
        /// </summary>
        public static string Descripcion_fecha_fin {
            get {
                return ResourceManager.GetString("Descripcion_fecha_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The start date begin at 00:00 of the selected day..
        /// </summary>
        public static string Descripcion_fecha_inicio {
            get {
                return ResourceManager.GetString("Descripcion_fecha_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        public static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo changes.
        /// </summary>
        public static string Deshacer_cambios {
            get {
                return ResourceManager.GetString("Deshacer_cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uncheck selected.
        /// </summary>
        public static string Desmarcar_seleccionados {
            get {
                return ResourceManager.GetString("Desmarcar_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string Detalle {
            get {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string Dia {
            get {
                return ResourceManager.GetString("Dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days.
        /// </summary>
        public static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max dimensions {0}x{1}..
        /// </summary>
        public static string Dimensiones_maximas {
            get {
                return ResourceManager.GetString("Dimensiones_maximas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edited by.
        /// </summary>
        public static string Editada_por {
            get {
                return ResourceManager.GetString("Editada_por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 selected element..
        /// </summary>
        public static string Elemento_seleccionado {
            get {
                return ResourceManager.GetString("Elemento_seleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a selected elements..
        /// </summary>
        public static string Elementos_seleccionados {
            get {
                return ResourceManager.GetString("Elementos_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 item deleted correctly:.
        /// </summary>
        public static string Eliminado_correcto {
            get {
                return ResourceManager.GetString("Eliminado_correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 item have not been removed correctly:.
        /// </summary>
        public static string Eliminado_fallido {
            get {
                return ResourceManager.GetString("Eliminado_fallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} items deleted correctly:.
        /// </summary>
        public static string Eliminados_correctos {
            get {
                return ResourceManager.GetString("Eliminados_correctos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} items have not been removed correctly:.
        /// </summary>
        public static string Eliminados_fallidos {
            get {
                return ResourceManager.GetString("Eliminados_fallidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing .
        /// </summary>
        public static string Eliminando {
            get {
                return ResourceManager.GetString("Eliminando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete selected file.
        /// </summary>
        public static string Eliminar_fichero_seleccionado {
            get {
                return ResourceManager.GetString("Eliminar_fichero_seleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the selected items?.
        /// </summary>
        public static string Eliminar_multiple_confirmacion {
            get {
                return ResourceManager.GetString("Eliminar_multiple_confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete selected.
        /// </summary>
        public static string Eliminar_seleccionados {
            get {
                return ResourceManager.GetString("Eliminar_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send verification code.
        /// </summary>
        public static string Enviar_codigo_verificacion {
            get {
                return ResourceManager.GetString("Enviar_codigo_verificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected category does not belong to the company..
        /// </summary>
        public static string Error_categoria_empresa {
            get {
                return ResourceManager.GetString("Error_categoria_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected client does not belong to the company..
        /// </summary>
        public static string Error_cliente_empresa {
            get {
                return ResourceManager.GetString("Error_cliente_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The start date has to be lower or equal than the end date..
        /// </summary>
        public static string Error_Comparar_Fechas {
            get {
                return ResourceManager.GetString("Error_Comparar_Fechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected driver does not belong to the company..
        /// </summary>
        public static string Error_conductor_empresa {
            get {
                return ResourceManager.GetString("Error_conductor_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} image does not match the maximum dimensions allowed ({1}x{2}). Please try again with another image..
        /// </summary>
        public static string Error_dimensiones_maximas {
            get {
                return ResourceManager.GetString("Error_dimensiones_maximas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company selected do not into the entity..
        /// </summary>
        public static string Error_empresa_id {
            get {
                return ResourceManager.GetString("Error_empresa_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected company is not sensoritation type..
        /// </summary>
        public static string Error_empresa_senso {
            get {
                return ResourceManager.GetString("Error_empresa_senso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected company is not telematic type..
        /// </summary>
        public static string Error_empresa_tele {
            get {
                return ResourceManager.GetString("Error_empresa_tele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected company is not trace type..
        /// </summary>
        public static string Error_empresa_trace {
            get {
                return ResourceManager.GetString("Error_empresa_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in date. The date or time is not correct or does not have the correct format. Standard formats:  &quot;dd/MM/yyyy&quot; , &quot;dd/MM/yyyy HH:mm:ss&quot;,  &quot;dd-MM-yyyy&quot; , &quot;dd-MM-yyyy HH:mm:ss&quot;.
        /// </summary>
        public static string Error_Fechas {
            get {
                return ResourceManager.GetString("Error_Fechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected fleet does not belong to the company..
        /// </summary>
        public static string Error_flota_empresa {
            get {
                return ResourceManager.GetString("Error_flota_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred while processing the image.
        /// </summary>
        public static string Error_imagen {
            get {
                return ResourceManager.GetString("Error_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error importing products.
        /// </summary>
        public static string Error_importar {
            get {
                return ResourceManager.GetString("Error_importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select at least one module..
        /// </summary>
        public static string Error_no_modulos {
            get {
                return ResourceManager.GetString("Error_no_modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select at least one telematics, traceability or sensorization module..
        /// </summary>
        public static string Error_no_modulos_tele_trace_senso {
            get {
                return ResourceManager.GetString("Error_no_modulos_tele_trace_senso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error processing the request..
        /// </summary>
        public static string Error_procesar {
            get {
                return ResourceManager.GetString("Error_procesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected product does not belong to the company..
        /// </summary>
        public static string Error_producto_empresa {
            get {
                return ResourceManager.GetString("Error_producto_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected supplier does not belong to the company..
        /// </summary>
        public static string Error_proveedor_empresa {
            get {
                return ResourceManager.GetString("Error_proveedor_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image path is not correct..
        /// </summary>
        public static string Error_ruta_imagen {
            get {
                return ResourceManager.GetString("Error_ruta_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected type is not valid..
        /// </summary>
        public static string Error_tipo_ubicacion {
            get {
                return ResourceManager.GetString("Error_tipo_ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected location does not belong to the company..
        /// </summary>
        public static string Error_ubicacion_empresa {
            get {
                return ResourceManager.GetString("Error_ubicacion_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected vehicle does not belong to the company..
        /// </summary>
        public static string Error_vehiculo_empresa {
            get {
                return ResourceManager.GetString("Error_vehiculo_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specify your email..
        /// </summary>
        public static string Especifique_correo {
            get {
                return ResourceManager.GetString("Especifique_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse ....
        /// </summary>
        public static string Examinar {
            get {
                return ResourceManager.GetString("Examinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception.
        /// </summary>
        public static string Excepcion {
            get {
                return ResourceManager.GetString("Excepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An exception was occurred.
        /// </summary>
        public static string Excepcion_producida {
            get {
                return ResourceManager.GetString("Excepcion_producida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success!.
        /// </summary>
        public static string Exito {
            get {
                return ResourceManager.GetString("Exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export to pdf.
        /// </summary>
        public static string ExportarPDF {
            get {
                return ResourceManager.GetString("ExportarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export to XLS.
        /// </summary>
        public static string ExportarXLS {
            get {
                return ResourceManager.GetString("ExportarXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a False.
        /// </summary>
        public static string Falso {
            get {
                return ResourceManager.GetString("Falso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation date.
        /// </summary>
        public static string Fecha_creacion {
            get {
                return ResourceManager.GetString("Fecha_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edition date.
        /// </summary>
        public static string Fecha_edicion {
            get {
                return ResourceManager.GetString("Fecha_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Printing date.
        /// </summary>
        public static string Fecha_impresion {
            get {
                return ResourceManager.GetString("Fecha_impresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        public static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type to filter....
        /// </summary>
        public static string Filtro_placeholder {
            get {
                return ResourceManager.GetString("Filtro_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fleet Management, Vehicle and Mobile Assets Tracking.
        /// </summary>
        public static string Gestion_flotas {
            get {
                return ResourceManager.GetString("Gestion_flotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Locations.
        /// </summary>
        public static string Gestionar_localizaciones {
            get {
                return ResourceManager.GetString("Gestionar_localizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for confirming your email..
        /// </summary>
        public static string Gracias_confirmar_email {
            get {
                return ResourceManager.GetString("Gracias_confirmar_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click here to login.
        /// </summary>
        public static string Hacer_click_iniciar {
            get {
                return ResourceManager.GetString("Hacer_click_iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Until.
        /// </summary>
        public static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello {0}!, show panel .
        /// </summary>
        public static string Hola {
            get {
                return ResourceManager.GetString("Hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour.
        /// </summary>
        public static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours.
        /// </summary>
        public static string Horas {
            get {
                return ResourceManager.GetString("Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ID {0} has not been found.
        /// </summary>
        public static string ID_no_encontrado {
            get {
                return ResourceManager.GetString("ID_no_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no element of type {0} with that ID.
        /// </summary>
        public static string ID_no_encontrado_descripcion {
            get {
                return ResourceManager.GetString("ID_no_encontrado_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must provide a valid ID.
        /// </summary>
        public static string ID_no_encontrado_vacio {
            get {
                return ResourceManager.GetString("ID_no_encontrado_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image not found.
        /// </summary>
        public static string Imagen_no_encontrada {
            get {
                return ResourceManager.GetString("Imagen_no_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importing products.
        /// </summary>
        public static string Importando_productos {
            get {
                return ResourceManager.GetString("Importando_productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Important: The first row of the document has to be the header..
        /// </summary>
        public static string Importante_excel {
            get {
                return ResourceManager.GetString("Importante_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select alarm type.
        /// </summary>
        public static string Indicar_tipo_alarma {
            get {
                return ResourceManager.GetString("Indicar_tipo_alarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select device type.
        /// </summary>
        public static string Indicar_tipo_dispositivo {
            get {
                return ResourceManager.GetString("Indicar_tipo_dispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We offer the status and onboard diagnosis, tracking and high definition video monitorization of your vehicle fleet, supported by a real time full analysis. This way we offer to our clients the most advanced plattform available in the market today..
        /// </summary>
        public static string Informacion_general {
            get {
                return ResourceManager.GetString("Informacion_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers access.
        /// </summary>
        public static string Iniciar_sesion {
            get {
                return ResourceManager.GetString("Iniciar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid login attempt..
        /// </summary>
        public static string Inicio_sesion_no_valido {
            get {
                return ResourceManager.GetString("Inicio_sesion_no_valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Inventory.
        /// </summary>
        public static string Inventario {
            get {
                return ResourceManager.GetString("Inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a logging ....
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} must be between {2} and {1} characters in length..
        /// </summary>
        public static string Longitud {
            get {
                return ResourceManager.GetString("Longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} can not have more than {1} characters in length..
        /// </summary>
        public static string Longitud_maxima {
            get {
                return ResourceManager.GetString("Longitud_maxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check all.
        /// </summary>
        public static string Marcar_todos {
            get {
                return ResourceManager.GetString("Marcar_todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your application description page..
        /// </summary>
        public static string Mensaje_about {
            get {
                return ResourceManager.GetString("Mensaje_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your contact page..
        /// </summary>
        public static string Mensaje_contact {
            get {
                return ResourceManager.GetString("Mensaje_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAIN MENU.
        /// </summary>
        public static string Menu_principal {
            get {
                return ResourceManager.GetString("Menu_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minute.
        /// </summary>
        public static string Minuto {
            get {
                return ResourceManager.GetString("Minuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minutes.
        /// </summary>
        public static string Minutos {
            get {
                return ResourceManager.GetString("Minutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify profile.
        /// </summary>
        public static string Modificar_perfil {
            get {
                return ResourceManager.GetString("Modificar_perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify company profile.
        /// </summary>
        public static string Modificar_perfil_empresa {
            get {
                return ResourceManager.GetString("Modificar_perfil_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify entity profile.
        /// </summary>
        public static string Modificar_perfil_entidad {
            get {
                return ResourceManager.GetString("Modificar_perfil_entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To access the requested page you must have the module {0}..
        /// </summary>
        public static string Modulo_no_disponible {
            get {
                return ResourceManager.GetString("Modulo_no_disponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please contact your administrator to request access to this module..
        /// </summary>
        public static string Modulo_no_disponible_descripcion {
            get {
                return ResourceManager.GetString("Modulo_no_disponible_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        public static string Mostrar {
            get {
                return ResourceManager.GetString("Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show filter.
        /// </summary>
        public static string Mostrar_filtro {
            get {
                return ResourceManager.GetString("Mostrar_filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} selected.
        /// </summary>
        public static string N_elementos_seleccionados {
            get {
                return ResourceManager.GetString("N_elementos_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No selected item.
        /// </summary>
        public static string Ningun_elemento_seleccionado {
            get {
                return ResourceManager.GetString("Ningun_elemento_seleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        public static string Ninguna {
            get {
                return ResourceManager.GetString("Ninguna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        public static string Ninguno {
            get {
                return ResourceManager.GetString("Ninguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fleet selected, please select one..
        /// </summary>
        public static string No_seleccionada_flota {
            get {
                return ResourceManager.GetString("No_seleccionada_flota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have permission to access the indicated url.
        /// </summary>
        public static string No_tiene_permiso {
            get {
                return ResourceManager.GetString("No_tiene_permiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications.
        /// </summary>
        public static string Notificaciones {
            get {
                return ResourceManager.GetString("Notificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide filter.
        /// </summary>
        public static string Ocultar_filtro {
            get {
                return ResourceManager.GetString("Ocultar_filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string Olvido_password {
            get {
                return ResourceManager.GetString("Olvido_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The requested operation was completed successfully..
        /// </summary>
        public static string Operacion_correcta {
            get {
                return ResourceManager.GetString("Operacion_correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please try after a few minutes and if the problem persists contact the administrator..
        /// </summary>
        public static string Operacion_incorrecta {
            get {
                return ResourceManager.GetString("Operacion_incorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regularization Operation.
        /// </summary>
        public static string Operacion_regularizacion {
            get {
                return ResourceManager.GetString("Operacion_regularizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organize.
        /// </summary>
        public static string Organizar {
            get {
                return ResourceManager.GetString("Organizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page.
        /// </summary>
        public static string Pagina {
            get {
                return ResourceManager.GetString("Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page not found.
        /// </summary>
        public static string Pagina_no_encontrada {
            get {
                return ResourceManager.GetString("Pagina_no_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The page you requested can not be found..
        /// </summary>
        public static string Pagina_no_encontrada_descripcion {
            get {
                return ResourceManager.GetString("Pagina_no_encontrada_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home screen.
        /// </summary>
        public static string Pantalla_inicial {
            get {
                return ResourceManager.GetString("Pantalla_inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IoT Vehicle and Fleet Monitoring Packages.
        /// </summary>
        public static string Paquete_seguimiento {
            get {
                return ResourceManager.GetString("Paquete_seguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password was reset..
        /// </summary>
        public static string Pass_restablecida {
            get {
                return ResourceManager.GetString("Pass_restablecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties.
        /// </summary>
        public static string Propiedades {
            get {
                return ResourceManager.GetString("Propiedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove the selected {0}..
        /// </summary>
        public static string Quitar_seleccionados {
            get {
                return ResourceManager.GetString("Quitar_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove all.
        /// </summary>
        public static string Quitar_todos {
            get {
                return ResourceManager.GetString("Quitar_todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferably .png with transparent background..
        /// </summary>
        public static string Recomendacion_imagen {
            get {
                return ResourceManager.GetString("Recomendacion_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESOURCES.
        /// </summary>
        public static string Recursos {
            get {
                return ResourceManager.GetString("Recursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        public static string Restablecer {
            get {
                return ResourceManager.GetString("Restablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        public static string Restablecer_pass {
            get {
                return ResourceManager.GetString("Restablecer_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To reset the password, click &lt;a href=&quot;{0}&quot;&gt; here &lt;/a&gt;.
        /// </summary>
        public static string Restablecer_pass_email {
            get {
                return ResourceManager.GetString("Restablecer_pass_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        public static string Restablezca_pass {
            get {
                return ResourceManager.GetString("Restablezca_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learn more.
        /// </summary>
        public static string Saber_mas {
            get {
                return ResourceManager.GetString("Saber_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second.
        /// </summary>
        public static string Segundo {
            get {
                return ResourceManager.GetString("Segundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seconds.
        /// </summary>
        public static string Segundos {
            get {
                return ResourceManager.GetString("Segundos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select file.
        /// </summary>
        public static string Seleccionar_fichero {
            get {
                return ResourceManager.GetString("Seleccionar_fichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the authentication provider in two phases:.
        /// </summary>
        public static string Seleccionar_proveedor_dorfases {
            get {
                return ResourceManager.GetString("Seleccionar_proveedor_dorfases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select all.
        /// </summary>
        public static string Seleccionar_todos {
            get {
                return ResourceManager.GetString("Seleccionar_todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no items to show.
        /// </summary>
        public static string Sin_elementos {
            get {
                return ResourceManager.GetString("Sin_elementos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support.
        /// </summary>
        public static string Soporte {
            get {
                return ResourceManager.GetString("Soporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IoT Platform.
        /// </summary>
        public static string Telematics {
            get {
                return ResourceManager.GetString("Telematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time in Inventory.
        /// </summary>
        public static string Tiempo_permanencia {
            get {
                return ResourceManager.GetString("Tiempo_permanencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string Todas {
            get {
                return ResourceManager.GetString("Todas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All selected.
        /// </summary>
        public static string Todos_elementos_seleccionados {
            get {
                return ResourceManager.GetString("Todos_elementos_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 selected.
        /// </summary>
        public static string Un_elemento_seleccionado {
            get {
                return ResourceManager.GetString("Un_elemento_seleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Image.
        /// </summary>
        public static string User_image {
            get {
                return ResourceManager.GetString("User_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only letters (uppercase and lowercase), numbers, spaces and characters &amp;&apos;- are allowed for the Description.
        /// </summary>
        public static string Validacion_descripcion {
            get {
                return ResourceManager.GetString("Validacion_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only letters (uppercase and lowercase) and numbers are allowed for the Identifier..
        /// </summary>
        public static string Validacion_identificador {
            get {
                return ResourceManager.GetString("Validacion_identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only letters (uppercase and lowercase), numbers, spaces and characters &amp;&apos;- are allowed for the Name.
        /// </summary>
        public static string Validacion_nombre {
            get {
                return ResourceManager.GetString("Validacion_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only letters (uppercase and lowercase) and numbers are allowed for the UID..
        /// </summary>
        public static string Validacion_UID {
            get {
                return ResourceManager.GetString("Validacion_UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a True.
        /// </summary>
        public static string Verdadero {
            get {
                return ResourceManager.GetString("Verdadero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check.
        /// </summary>
        public static string Verificar {
            get {
                return ResourceManager.GetString("Verificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email link.
        /// </summary>
        public static string Vinculo_correo {
            get {
                return ResourceManager.GetString("Vinculo_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General view.
        /// </summary>
        public static string Vista_general {
            get {
                return ResourceManager.GetString("Vista_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to {0}.
        /// </summary>
        public static string Volver_a {
            get {
                return ResourceManager.GetString("Volver_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to index.
        /// </summary>
        public static string Volver_indice {
            get {
                return ResourceManager.GetString("Volver_indice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Volver_lista {
            get {
                return ResourceManager.GetString("Volver_lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
