//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notificaciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notificaciones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Notificaciones", typeof(Notificaciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is required..
        /// </summary>
        public static string Campo_vacio {
            get {
                return ResourceManager.GetString("Campo_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is required and does not have a default value..
        /// </summary>
        public static string Campo_vacio_sin_defecto {
            get {
                return ResourceManager.GetString("Campo_vacio_sin_defecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Notification.
        /// </summary>
        public static string Crear_notificacion {
            get {
                return ResourceManager.GetString("Crear_notificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing notification.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new notification.
        /// </summary>
        public static string Descripcion_creacion {
            get {
                return ResourceManager.GetString("Descripcion_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing notification.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing notification.
        /// </summary>
        public static string Descripcion_edicion {
            get {
                return ResourceManager.GetString("Descripcion_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Notification.
        /// </summary>
        public static string Editar_notificacion {
            get {
                return ResourceManager.GetString("Editar_notificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected notification?.
        /// </summary>
        public static string Encabezado_borrado {
            get {
                return ResourceManager.GetString("Encabezado_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new notification below.
        /// </summary>
        public static string Encabezado_creacion {
            get {
                return ResourceManager.GetString("Encabezado_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected notification is shown below.
        /// </summary>
        public static string Encabezado_detalles {
            get {
                return ResourceManager.GetString("Encabezado_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the notification below.
        /// </summary>
        public static string Encabezado_edicion {
            get {
                return ResourceManager.GetString("Encabezado_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation date.
        /// </summary>
        public static string Fecha_creacion {
            get {
                return ResourceManager.GetString("Fecha_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read date.
        /// </summary>
        public static string Fecha_lectura {
            get {
                return ResourceManager.GetString("Fecha_lectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read?.
        /// </summary>
        public static string Leida {
            get {
                return ResourceManager.GetString("Leida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show general notifications only.
        /// </summary>
        public static string Mostrar_notificaciones_generales {
            get {
                return ResourceManager.GetString("Mostrar_notificaciones_generales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No new notifications.
        /// </summary>
        public static string Ninguna {
            get {
                return ResourceManager.GetString("Ninguna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications.
        /// </summary>
        public static string Notificacion {
            get {
                return ResourceManager.GetString("Notificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification {0} has not been created..
        /// </summary>
        public static string Notificacion_creada_error {
            get {
                return ResourceManager.GetString("Notificacion_creada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification {0} has been successfully created..
        /// </summary>
        public static string Notificacion_creada_exito {
            get {
                return ResourceManager.GetString("Notificacion_creada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification {0} has not been edited..
        /// </summary>
        public static string Notificacion_editada_error {
            get {
                return ResourceManager.GetString("Notificacion_editada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification {0} has been successfully edited..
        /// </summary>
        public static string Notificacion_editada_exito {
            get {
                return ResourceManager.GetString("Notificacion_editada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification {0} has not been deleted..
        /// </summary>
        public static string Notificacion_eliminada_error {
            get {
                return ResourceManager.GetString("Notificacion_eliminada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The notification {0} has been successfully deleted..
        /// </summary>
        public static string Notificacion_eliminada_exito {
            get {
                return ResourceManager.GetString("Notificacion_eliminada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General notification.
        /// </summary>
        public static string Notificacion_general {
            get {
                return ResourceManager.GetString("Notificacion_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notification.
        /// </summary>
        public static string Notificacion_simple {
            get {
                return ResourceManager.GetString("Notificacion_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications per page:.
        /// </summary>
        public static string Notificaciones_pagina {
            get {
                return ResourceManager.GetString("Notificaciones_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select companies.
        /// </summary>
        public static string Seleccionar_empresas {
            get {
                return ResourceManager.GetString("Seleccionar_empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directed to.
        /// </summary>
        public static string Seleccionar_empresas_flotas {
            get {
                return ResourceManager.GetString("Seleccionar_empresas_flotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select fleets.
        /// </summary>
        public static string Seleccionar_flotas {
            get {
                return ResourceManager.GetString("Seleccionar_flotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select to whom the notification will be destined. If you select the &quot;all&quot; option, the notification will be sent to all users..
        /// </summary>
        public static string Texto_seleccion_empresas {
            get {
                return ResourceManager.GetString("Texto_seleccion_empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the entities or companies to assign the notification. If you select the option &quot;all&quot; the notification will be shown to all users of any entity or company..
        /// </summary>
        public static string Texto_seleccion_empresas_admin {
            get {
                return ResourceManager.GetString("Texto_seleccion_empresas_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has {0} notifications.
        /// </summary>
        public static string Tiene {
            get {
                return ResourceManager.GetString("Tiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string Tipo_advertencia {
            get {
                return ResourceManager.GetString("Tipo_advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        public static string Tipo_alerta {
            get {
                return ResourceManager.GetString("Tipo_alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string Tipo_exito {
            get {
                return ResourceManager.GetString("Tipo_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        public static string Tipo_informacion {
            get {
                return ResourceManager.GetString("Tipo_informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message type.
        /// </summary>
        public static string Tipo_mensaje {
            get {
                return ResourceManager.GetString("Tipo_mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string Tipo_normal {
            get {
                return ResourceManager.GetString("Tipo_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show All.
        /// </summary>
        public static string Ver_todas {
            get {
                return ResourceManager.GetString("Ver_todas", resourceCulture);
            }
        }
    }
}
