//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ordenes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ordenes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Ordenes", typeof(Ordenes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order you want to delete has associated assets. Please delete them and try again..
        /// </summary>
        public static string Activo_asociado {
            get {
                return ResourceManager.GetString("Activo_asociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage.
        /// </summary>
        public static string Almacen {
            get {
                return ResourceManager.GetString("Almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Storage.
        /// </summary>
        public static string Almacen_cliente {
            get {
                return ResourceManager.GetString("Almacen_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination Storage.
        /// </summary>
        public static string Almacen_destino {
            get {
                return ResourceManager.GetString("Almacen_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origin Storage.
        /// </summary>
        public static string Almacen_origen {
            get {
                return ResourceManager.GetString("Almacen_origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider Storage.
        /// </summary>
        public static string Almacen_proveedor {
            get {
                return ResourceManager.GetString("Almacen_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Product.
        /// </summary>
        public static string Añadir_producto {
            get {
                return ResourceManager.GetString("Añadir_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excel FIle.
        /// </summary>
        public static string Archivo_excel {
            get {
                return ResourceManager.GetString("Archivo_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shopping cart is empty, please, add a product first..
        /// </summary>
        public static string Carrito_vacio {
            get {
                return ResourceManager.GetString("Carrito_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed.
        /// </summary>
        public static string Completado {
            get {
                return ResourceManager.GetString("Completado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase.
        /// </summary>
        public static string Compra {
            get {
                return ResourceManager.GetString("Compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details Data.
        /// </summary>
        public static string Datos_detalle {
            get {
                return ResourceManager.GetString("Datos_detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Data.
        /// </summary>
        public static string Datos_generales {
            get {
                return ResourceManager.GetString("Datos_generales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a storage to display the available transfer orders..
        /// </summary>
        public static string Debe_seleccionar_almacen {
            get {
                return ResourceManager.GetString("Debe_seleccionar_almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing Purchase Order.
        /// </summary>
        public static string Descripcion_borrado_compra {
            get {
                return ResourceManager.GetString("Descripcion_borrado_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing Pick List.
        /// </summary>
        public static string Descripcion_borrado_picklist {
            get {
                return ResourceManager.GetString("Descripcion_borrado_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing Transfer Order.
        /// </summary>
        public static string Descripcion_borrado_transferencia {
            get {
                return ResourceManager.GetString("Descripcion_borrado_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing Sale Order.
        /// </summary>
        public static string Descripcion_borrado_venta {
            get {
                return ResourceManager.GetString("Descripcion_borrado_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new Purchase Order.
        /// </summary>
        public static string Descripcion_creacion_compra {
            get {
                return ResourceManager.GetString("Descripcion_creacion_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new Pick List.
        /// </summary>
        public static string Descripcion_creacion_picklist {
            get {
                return ResourceManager.GetString("Descripcion_creacion_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new Transfer Order.
        /// </summary>
        public static string Descripcion_creacion_transferencia {
            get {
                return ResourceManager.GetString("Descripcion_creacion_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new Sale Order.
        /// </summary>
        public static string Descripcion_creacion_venta {
            get {
                return ResourceManager.GetString("Descripcion_creacion_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing Purchase Order.
        /// </summary>
        public static string Descripcion_detalles_compra {
            get {
                return ResourceManager.GetString("Descripcion_detalles_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing Pick List.
        /// </summary>
        public static string Descripcion_detalles_picklist {
            get {
                return ResourceManager.GetString("Descripcion_detalles_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing Transfer Order.
        /// </summary>
        public static string Descripcion_detalles_transferencia {
            get {
                return ResourceManager.GetString("Descripcion_detalles_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing Sale Order.
        /// </summary>
        public static string Descripcion_detalles_venta {
            get {
                return ResourceManager.GetString("Descripcion_detalles_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing Purchase Order.
        /// </summary>
        public static string Descripcion_edicion_compra {
            get {
                return ResourceManager.GetString("Descripcion_edicion_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing Pick List.
        /// </summary>
        public static string Descripcion_edicion_picklist {
            get {
                return ResourceManager.GetString("Descripcion_edicion_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing Transfer Order.
        /// </summary>
        public static string Descripcion_edicion_transferencia {
            get {
                return ResourceManager.GetString("Descripcion_edicion_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing Sale Order.
        /// </summary>
        public static string Descripcion_edicion_venta {
            get {
                return ResourceManager.GetString("Descripcion_edicion_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase Orders stored in system.
        /// </summary>
        public static string Descripcion_index_compra {
            get {
                return ResourceManager.GetString("Descripcion_index_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Lists stored in system.
        /// </summary>
        public static string Descripcion_index_picklist {
            get {
                return ResourceManager.GetString("Descripcion_index_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfers Orders stored in system.
        /// </summary>
        public static string Descripcion_index_transferencia {
            get {
                return ResourceManager.GetString("Descripcion_index_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sales Orders stored in system.
        /// </summary>
        public static string Descripcion_index_venta {
            get {
                return ResourceManager.GetString("Descripcion_index_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details for the transfer order..
        /// </summary>
        public static string Detalles_ordenes_transferencia {
            get {
                return ResourceManager.GetString("Detalles_ordenes_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This company has not associated customers yet..
        /// </summary>
        public static string Empresa_sin_cliente {
            get {
                return ResourceManager.GetString("Empresa_sin_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This company has not associated suppliers yet..
        /// </summary>
        public static string Empresa_sin_proveedor {
            get {
                return ResourceManager.GetString("Empresa_sin_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This company has not associated locations yet..
        /// </summary>
        public static string Empresa_sin_ubicacion {
            get {
                return ResourceManager.GetString("Empresa_sin_ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On hold.
        /// </summary>
        public static string En_espera {
            get {
                return ResourceManager.GetString("En_espera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected Purchase Order?.
        /// </summary>
        public static string Encabezado_borrado_compra {
            get {
                return ResourceManager.GetString("Encabezado_borrado_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected Pick List?.
        /// </summary>
        public static string Encabezado_borrado_picklist {
            get {
                return ResourceManager.GetString("Encabezado_borrado_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected Transfer Order?.
        /// </summary>
        public static string Encabezado_borrado_transferencia {
            get {
                return ResourceManager.GetString("Encabezado_borrado_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected Sale Order?.
        /// </summary>
        public static string Encabezado_borrado_venta {
            get {
                return ResourceManager.GetString("Encabezado_borrado_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new Purchase Order below.
        /// </summary>
        public static string Encabezado_creacion_compra {
            get {
                return ResourceManager.GetString("Encabezado_creacion_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new Pick List below.
        /// </summary>
        public static string Encabezado_creacion_picklist {
            get {
                return ResourceManager.GetString("Encabezado_creacion_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new Transfer Order below.
        /// </summary>
        public static string Encabezado_creacion_transferencia {
            get {
                return ResourceManager.GetString("Encabezado_creacion_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new Sale Order below.
        /// </summary>
        public static string Encabezado_creacion_venta {
            get {
                return ResourceManager.GetString("Encabezado_creacion_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected Purchase Order is shown below.
        /// </summary>
        public static string Encabezado_detalles_compra {
            get {
                return ResourceManager.GetString("Encabezado_detalles_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected Pick List is shown below.
        /// </summary>
        public static string Encabezado_detalles_picklist {
            get {
                return ResourceManager.GetString("Encabezado_detalles_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected Transfer Order is shown below.
        /// </summary>
        public static string Encabezado_detalles_transferencia {
            get {
                return ResourceManager.GetString("Encabezado_detalles_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected Sale Order is shown below.
        /// </summary>
        public static string Encabezado_detalles_venta {
            get {
                return ResourceManager.GetString("Encabezado_detalles_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the Purchase Order below.
        /// </summary>
        public static string Encabezado_edicion_compra {
            get {
                return ResourceManager.GetString("Encabezado_edicion_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the Pick List below.
        /// </summary>
        public static string Encabezado_edicion_picklist {
            get {
                return ResourceManager.GetString("Encabezado_edicion_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the Transfer Order below.
        /// </summary>
        public static string Encabezado_edicion_transferencia {
            get {
                return ResourceManager.GetString("Encabezado_edicion_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the Sale Order below.
        /// </summary>
        public static string Encabezado_edicion_venta {
            get {
                return ResourceManager.GetString("Encabezado_edicion_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entity.
        /// </summary>
        public static string Entidad {
            get {
                return ResourceManager.GetString("Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The picklist could not be generated because there are no available assets of the selected products. It&apos;s possible that the assets are already in the location selected as destination; please, check it..
        /// </summary>
        public static string Error_activos_disponibles {
            get {
                return ResourceManager.GetString("Error_activos_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect amount..
        /// </summary>
        public static string Error_DetalleOrden_Cantidad {
            get {
                return ResourceManager.GetString("Error_DetalleOrden_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect TipoActivoId..
        /// </summary>
        public static string Error_DetalleOrden_TipoActivoId {
            get {
                return ResourceManager.GetString("Error_DetalleOrden_TipoActivoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Super Operator User and there is no Company to assign, or the Company does not exist, or the User Company does not match the Company that is passed by parameter.
        /// </summary>
        public static string Error_Empresa_Id {
            get {
                return ResourceManager.GetString("Error_Empresa_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred with the order date. Please try again..
        /// </summary>
        public static string Error_fecha {
            get {
                return ResourceManager.GetString("Error_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred with the picklist date. Please try again..
        /// </summary>
        public static string Error_fecha_picklist {
            get {
                return ResourceManager.GetString("Error_fecha_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not edit the destination storage of a transfer order associated to a picklist..
        /// </summary>
        public static string Error_orden_asociada_picklist {
            get {
                return ResourceManager.GetString("Error_orden_asociada_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select product or code and stock columns.
        /// </summary>
        public static string Error_seleccionar_columnas {
            get {
                return ResourceManager.GetString("Error_seleccionar_columnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file has not been uploaded.
        /// </summary>
        public static string Error_subida {
            get {
                return ResourceManager.GetString("Error_subida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The destination location value is not valid.
        /// </summary>
        public static string Error_ubicacion_destino {
            get {
                return ResourceManager.GetString("Error_ubicacion_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location does not exist in the current company.
        /// </summary>
        public static string Error_Ubicacion_Empresa {
            get {
                return ResourceManager.GetString("Error_Ubicacion_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The origin location value is not valid.
        /// </summary>
        public static string Error_ubicacion_origen {
            get {
                return ResourceManager.GetString("Error_ubicacion_origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The location can not be empty.
        /// </summary>
        public static string Error_Ubicacion_Vacia {
            get {
                return ResourceManager.GetString("Error_Ubicacion_Vacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Origin Location and the Destination Location have to be different.
        /// </summary>
        public static string Error_Ubicaciones_Iguales {
            get {
                return ResourceManager.GetString("Error_Ubicaciones_Iguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter by state.
        /// </summary>
        public static string Filtrar_estado {
            get {
                return ResourceManager.GetString("Filtrar_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Number.
        /// </summary>
        public static string Identificador {
            get {
                return ResourceManager.GetString("Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order identifier is already in use, please try another..
        /// </summary>
        public static string Identificador_en_uso {
            get {
                return ResourceManager.GetString("Identificador_en_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import Excel.
        /// </summary>
        public static string Importar_excel {
            get {
                return ResourceManager.GetString("Importar_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initiated.
        /// </summary>
        public static string Iniciado {
            get {
                return ResourceManager.GetString("Iniciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show locations.
        /// </summary>
        public static string Mostrar_ubicaciones {
            get {
                return ResourceManager.GetString("Mostrar_ubicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reasons: .
        /// </summary>
        public static string Motivo {
            get {
                return ResourceManager.GetString("Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        public static string Ninguna {
            get {
                return ResourceManager.GetString("Ninguna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The work order destination does not correspond to the current location, so the operation can not be associated with that order..
        /// </summary>
        public static string No_coincide_destino {
            get {
                return ResourceManager.GetString("No_coincide_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The work order origin does not correspond to the current location, so the operation can not be associated to that order..
        /// </summary>
        public static string No_coincide_origen {
            get {
                return ResourceManager.GetString("No_coincide_origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No company selected..
        /// </summary>
        public static string No_empresa {
            get {
                return ResourceManager.GetString("No_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfer orders available at this moment for the selected storage..
        /// </summary>
        public static string No_hay_ot_disponibles {
            get {
                return ResourceManager.GetString("No_hay_ot_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfer orders selected yet..
        /// </summary>
        public static string No_hay_ot_seleccionadas {
            get {
                return ResourceManager.GetString("No_hay_ot_seleccionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not any Products to show at this moment..
        /// </summary>
        public static string No_hay_productos {
            get {
                return ResourceManager.GetString("No_hay_productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No work order origin selected..
        /// </summary>
        public static string No_origen {
            get {
                return ResourceManager.GetString("No_origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not edit the selected order because its status is different from &quot;On Hold&quot;..
        /// </summary>
        public static string No_puede_editar {
            get {
                return ResourceManager.GetString("No_puede_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not delete the selected order because its status is &quot;Started&quot;..
        /// </summary>
        public static string No_puede_eliminar {
            get {
                return ResourceManager.GetString("No_puede_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Purchase Order.
        /// </summary>
        public static string Nueva_orden_compra {
            get {
                return ResourceManager.GetString("Nueva_orden_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Transfer Order.
        /// </summary>
        public static string Nueva_orden_transferencia {
            get {
                return ResourceManager.GetString("Nueva_orden_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Sale Order.
        /// </summary>
        public static string Nueva_orden_venta {
            get {
                return ResourceManager.GetString("Nueva_orden_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Pick List.
        /// </summary>
        public static string Nueva_picklist {
            get {
                return ResourceManager.GetString("Nueva_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order you want to delete is associated with an operation, so it can not be deleted..
        /// </summary>
        public static string Operacion_asociada {
            get {
                return ResourceManager.GetString("Operacion_asociada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed order.
        /// </summary>
        public static string Orden_completa {
            get {
                return ResourceManager.GetString("Orden_completa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase Order.
        /// </summary>
        public static string Orden_compra {
            get {
                return ResourceManager.GetString("Orden_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order {0} has not been created..
        /// </summary>
        public static string Orden_creada_error {
            get {
                return ResourceManager.GetString("Orden_creada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order {0} has been successfully created..
        /// </summary>
        public static string Orden_creada_exito {
            get {
                return ResourceManager.GetString("Orden_creada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order {0} has not been edited..
        /// </summary>
        public static string Orden_editada_error {
            get {
                return ResourceManager.GetString("Orden_editada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order {0} has been successfully edited..
        /// </summary>
        public static string Orden_editada_exito {
            get {
                return ResourceManager.GetString("Orden_editada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order {0} has not been deleted..
        /// </summary>
        public static string Orden_eliminada_error {
            get {
                return ResourceManager.GetString("Orden_eliminada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order {0} has been successfully deleted..
        /// </summary>
        public static string Orden_eliminada_exito {
            get {
                return ResourceManager.GetString("Orden_eliminada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No order has been found that corresponds to the type and number indicated..
        /// </summary>
        public static string Orden_no_encontrada {
            get {
                return ResourceManager.GetString("Orden_no_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No transfer order has been generated because all of the selected products are in the destination store..
        /// </summary>
        public static string Orden_no_generada {
            get {
                return ResourceManager.GetString("Orden_no_generada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The creation of one or more transfer orders has been omitted or the quantity of products included is less than that requested because part of the selected products are not available..
        /// </summary>
        public static string Orden_omitida {
            get {
                return ResourceManager.GetString("Orden_omitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order without Details..
        /// </summary>
        public static string Orden_sin_detalles {
            get {
                return ResourceManager.GetString("Orden_sin_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not create an order without an associated date. Please, try again..
        /// </summary>
        public static string Orden_sin_fecha {
            get {
                return ResourceManager.GetString("Orden_sin_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not create an order without an associated identifier. Please try again..
        /// </summary>
        public static string Orden_sin_identificador {
            get {
                return ResourceManager.GetString("Orden_sin_identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer Order.
        /// </summary>
        public static string Orden_transferencia {
            get {
                return ResourceManager.GetString("Orden_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sale Order.
        /// </summary>
        public static string Orden_venta {
            get {
                return ResourceManager.GetString("Orden_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending Purchase Orders.
        /// </summary>
        public static string Ordenes_compra_pendientes {
            get {
                return ResourceManager.GetString("Ordenes_compra_pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Transfer Orders.
        /// </summary>
        public static string Ordenes_disponibles {
            get {
                return ResourceManager.GetString("Ordenes_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orders per page.
        /// </summary>
        public static string Ordenes_pagina {
            get {
                return ResourceManager.GetString("Ordenes_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected Transfer Orders.
        /// </summary>
        public static string Ordenes_seleccionadas {
            get {
                return ResourceManager.GetString("Ordenes_seleccionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending Transfer Orders.
        /// </summary>
        public static string Ordenes_transferencia_pendientes {
            get {
                return ResourceManager.GetString("Ordenes_transferencia_pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending Sale Orders.
        /// </summary>
        public static string Ordenes_venta_pendientes {
            get {
                return ResourceManager.GetString("Ordenes_venta_pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The origin and destination storages can not be the same. Please, select a different one..
        /// </summary>
        public static string Origen_y_destino_iguales {
            get {
                return ResourceManager.GetString("Origen_y_destino_iguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick List.
        /// </summary>
        public static string Pick_list {
            get {
                return ResourceManager.GetString("Pick_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pick list {0} has not been created..
        /// </summary>
        public static string PickList_creada_error {
            get {
                return ResourceManager.GetString("PickList_creada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pick list {0} has been successfully created..
        /// </summary>
        public static string PickList_creada_exito {
            get {
                return ResourceManager.GetString("PickList_creada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pick list {0} has not been edited..
        /// </summary>
        public static string PickList_editada_error {
            get {
                return ResourceManager.GetString("PickList_editada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pick list {0} has been successfully edited..
        /// </summary>
        public static string PickList_editada_exito {
            get {
                return ResourceManager.GetString("PickList_editada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pick list {0} has not been deleted..
        /// </summary>
        public static string PickList_eliminada_error {
            get {
                return ResourceManager.GetString("PickList_eliminada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pick list {0} has been successfully deleted..
        /// </summary>
        public static string PickList_eliminada_exito {
            get {
                return ResourceManager.GetString("PickList_eliminada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The identifier of the picklist is already in use, please try another..
        /// </summary>
        public static string Picklist_identificador_en_uso {
            get {
                return ResourceManager.GetString("Picklist_identificador_en_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not edit the selected picklist because its status is different from &quot;On Hold&quot;..
        /// </summary>
        public static string Picklist_no_puede_editar {
            get {
                return ResourceManager.GetString("Picklist_no_puede_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not delete the selected picklist because its status is &quot;Started&quot;..
        /// </summary>
        public static string Picklist_no_puede_eliminar {
            get {
                return ResourceManager.GetString("Picklist_no_puede_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not create a picklist without an associated date. Please try again..
        /// </summary>
        public static string Picklist_sin_fecha {
            get {
                return ResourceManager.GetString("Picklist_sin_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not create a picklist without an associated identifier. Please try again..
        /// </summary>
        public static string Picklist_sin_identificador {
            get {
                return ResourceManager.GetString("Picklist_sin_identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not create a picklist without an associated order. Please try again..
        /// </summary>
        public static string Picklist_sin_orden {
            get {
                return ResourceManager.GetString("Picklist_sin_orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Lists.
        /// </summary>
        public static string PickLists {
            get {
                return ResourceManager.GetString("PickLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Lists per page.
        /// </summary>
        public static string Picklists_pagina {
            get {
                return ResourceManager.GetString("Picklists_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending Pick Lists.
        /// </summary>
        public static string Picklists_pendientes {
            get {
                return ResourceManager.GetString("Picklists_pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} does not exist.
        /// </summary>
        public static string Producto_no_encontrado {
            get {
                return ResourceManager.GetString("Producto_no_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} does not currently have stock..
        /// </summary>
        public static string Producto_sin_stock {
            get {
                return ResourceManager.GetString("Producto_sin_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} stock is not enough for the requested quantity ({1}), the maximum available stock ({2}) has been established..
        /// </summary>
        public static string Producto_stock_insuficiente {
            get {
                return ResourceManager.GetString("Producto_stock_insuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products not imported:.
        /// </summary>
        public static string Productos_importados_error {
            get {
                return ResourceManager.GetString("Productos_importados_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products imported correctly: .
        /// </summary>
        public static string Productos_importados_exito {
            get {
                return ResourceManager.GetString("Productos_importados_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplier.
        /// </summary>
        public static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suppliers.
        /// </summary>
        public static string Proveedores {
            get {
                return ResourceManager.GetString("Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import Result.
        /// </summary>
        public static string Resultado_importacion {
            get {
                return ResourceManager.GetString("Resultado_importacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload File.
        /// </summary>
        public static string Subir_archivo {
            get {
                return ResourceManager.GetString("Subir_archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Purchase Order.
        /// </summary>
        public static string Titulo_crear_compra {
            get {
                return ResourceManager.GetString("Titulo_crear_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Pick List.
        /// </summary>
        public static string Titulo_crear_picklist {
            get {
                return ResourceManager.GetString("Titulo_crear_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Transfer Order.
        /// </summary>
        public static string Titulo_crear_transferencia {
            get {
                return ResourceManager.GetString("Titulo_crear_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Sale Order.
        /// </summary>
        public static string Titulo_crear_venta {
            get {
                return ResourceManager.GetString("Titulo_crear_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Purchase Order.
        /// </summary>
        public static string Titulo_editar_compra {
            get {
                return ResourceManager.GetString("Titulo_editar_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Pick List.
        /// </summary>
        public static string Titulo_editar_picklist {
            get {
                return ResourceManager.GetString("Titulo_editar_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Transfer Order.
        /// </summary>
        public static string Titulo_editar_transferencia {
            get {
                return ResourceManager.GetString("Titulo_editar_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Sale Order.
        /// </summary>
        public static string Titulo_editar_venta {
            get {
                return ResourceManager.GetString("Titulo_editar_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Purchase Order.
        /// </summary>
        public static string Titulo_eliminar_compra {
            get {
                return ResourceManager.GetString("Titulo_eliminar_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Pick List.
        /// </summary>
        public static string Titulo_eliminar_picklist {
            get {
                return ResourceManager.GetString("Titulo_eliminar_picklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Transfer Order.
        /// </summary>
        public static string Titulo_eliminar_transferencia {
            get {
                return ResourceManager.GetString("Titulo_eliminar_transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Sale Order.
        /// </summary>
        public static string Titulo_eliminar_venta {
            get {
                return ResourceManager.GetString("Titulo_eliminar_venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer.
        /// </summary>
        public static string Transferencia {
            get {
                return ResourceManager.GetString("Transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Orders Created.
        /// </summary>
        public static string Ultimas_ordenes_creadas {
            get {
                return ResourceManager.GetString("Ultimas_ordenes_creadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sale.
        /// </summary>
        public static string Venta {
            get {
                return ResourceManager.GetString("Venta", resourceCulture);
            }
        }
    }
}
