//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TiposActivos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TiposActivos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.TiposActivos", typeof(TiposActivos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assets.
        /// </summary>
        public static string Activos {
            get {
                return ResourceManager.GetString("Activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product you want to delete is associated with some asset, so it can not be deleted; please delete the assets and try again..
        /// </summary>
        public static string Activos_asociados {
            get {
                return ResourceManager.GetString("Activos_asociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assets associated with the product.
        /// </summary>
        public static string Activos_asociados_al_producto {
            get {
                return ResourceManager.GetString("Activos_asociados_al_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} that you want to delete has associated assets; if you delete it, those assets will also be deleted, are you sure?.
        /// </summary>
        public static string Advertencia_eliminar_activos {
            get {
                return ResourceManager.GetString("Advertencia_eliminar_activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} has not been added to the basket..
        /// </summary>
        public static string Añadido_cesta_error {
            get {
                return ResourceManager.GetString("Añadido_cesta_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} has been successfully added to the basket..
        /// </summary>
        public static string Añadido_cesta_exito {
            get {
                return ResourceManager.GetString("Añadido_cesta_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Añadir {
            get {
                return ResourceManager.GetString("Añadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced Search.
        /// </summary>
        public static string Busqueda_avanzada {
            get {
                return ResourceManager.GetString("Busqueda_avanzada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple Search.
        /// </summary>
        public static string Busqueda_simple {
            get {
                return ResourceManager.GetString("Busqueda_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Sort.
        /// </summary>
        public static string Cambio_ordenacion {
            get {
                return ResourceManager.GetString("Cambio_ordenacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product has not been created because some required fields have not been entered..
        /// </summary>
        public static string Campo_requerido {
            get {
                return ResourceManager.GetString("Campo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available fields.
        /// </summary>
        public static string Campos_disponibles {
            get {
                return ResourceManager.GetString("Campos_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of row.
        /// </summary>
        public static string de_la_fila {
            get {
                return ResourceManager.GetString("de_la_fila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing product.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new product.
        /// </summary>
        public static string Descripcion_creacion {
            get {
                return ResourceManager.GetString("Descripcion_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing product.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit an existing product.
        /// </summary>
        public static string Descripcion_edicion {
            get {
                return ResourceManager.GetString("Descripcion_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product you are trying to edit has assets associated assets. If you edit the product, all assets associated with that product will be subject to these changes..
        /// </summary>
        public static string Editar_con_activos {
            get {
                return ResourceManager.GetString("Editar_con_activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The entered value .
        /// </summary>
        public static string El_valor {
            get {
                return ResourceManager.GetString("El_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} has not been removed from the basket..
        /// </summary>
        public static string Eliminado_cesta_error {
            get {
                return ResourceManager.GetString("Eliminado_cesta_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product {0} has been successfully removed from the basket..
        /// </summary>
        public static string Eliminado_cesta_exito {
            get {
                return ResourceManager.GetString("Eliminado_cesta_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected product?.
        /// </summary>
        public static string Encabezado_borrado {
            get {
                return ResourceManager.GetString("Encabezado_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new product below.
        /// </summary>
        public static string Encabezado_creacion {
            get {
                return ResourceManager.GetString("Encabezado_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected product is shown below.
        /// </summary>
        public static string Encabezado_detalles {
            get {
                return ResourceManager.GetString("Encabezado_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the product below.
        /// </summary>
        public static string Encabezado_edicion {
            get {
                return ResourceManager.GetString("Encabezado_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred when processing the image..
        /// </summary>
        public static string Error_imagen {
            get {
                return ResourceManager.GetString("Error_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any of the entered values do not match the type of data that was expected..
        /// </summary>
        public static string Error_tipo {
            get {
                return ResourceManager.GetString("Error_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Assets.
        /// </summary>
        public static string Examinar {
            get {
                return ResourceManager.GetString("Examinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Before creating a product there must be a category to which to assign that type; please, create the new category..
        /// </summary>
        public static string Falta_categoria {
            get {
                return ResourceManager.GetString("Falta_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Row.
        /// </summary>
        public static string Fila {
            get {
                return ResourceManager.GetString("Fila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate Pick List.
        /// </summary>
        public static string Generar_PickList {
            get {
                return ResourceManager.GetString("Generar_PickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grid.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Image.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image not found in the specified path..
        /// </summary>
        public static string Imagen_no_encontrada {
            get {
                return ResourceManager.GetString("Imagen_no_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import Products.
        /// </summary>
        public static string Importar {
            get {
                return ResourceManager.GetString("Importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a does not correspond to the data type expected.
        /// </summary>
        public static string no_corresponde {
            get {
                return ResourceManager.GetString("no_corresponde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no assets associated with this product. .
        /// </summary>
        public static string No_existen {
            get {
                return ResourceManager.GetString("No_existen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is not an image associated with this product.
        /// </summary>
        public static string No_imagen {
            get {
                return ResourceManager.GetString("No_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no products in this location.
        /// </summary>
        public static string No_productos_localizacion {
            get {
                return ResourceManager.GetString("No_productos_localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product name is already in use..
        /// </summary>
        public static string Nombre_repetido {
            get {
                return ResourceManager.GetString("Nombre_repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New product.
        /// </summary>
        public static string Nuevo_tipo_de_activo {
            get {
                return ResourceManager.GetString("Nuevo_tipo_de_activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assets:.
        /// </summary>
        public static string Numero_activos {
            get {
                return ResourceManager.GetString("Numero_activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available:.
        /// </summary>
        public static string Numero_activos_disponibles {
            get {
                return ResourceManager.GetString("Numero_activos_disponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order by.
        /// </summary>
        public static string Ordenar_por {
            get {
                return ResourceManager.GetString("Ordenar_por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product you want to delete is associated with a purchase order, so it can not be deleted; please delete the purchase order and try again. .
        /// </summary>
        public static string Ordenes_compra_asociadas {
            get {
                return ResourceManager.GetString("Ordenes_compra_asociadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product you want to delete is associated with a transfer order, so it can not be deleted; please delete the transfer order and try again. .
        /// </summary>
        public static string Ordenes_transferencia_asociadas {
            get {
                return ResourceManager.GetString("Ordenes_transferencia_asociadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product you want to delete is associated with a sales order, so it can not be deleted; please delete the sales order and try again. .
        /// </summary>
        public static string Ordenes_venta_asociadas {
            get {
                return ResourceManager.GetString("Ordenes_venta_asociadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the date and the destination store below..
        /// </summary>
        public static string Seleccione_fecha_y_almacen {
            get {
                return ResourceManager.GetString("Seleccione_fecha_y_almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has {0} products added.
        /// </summary>
        public static string Tiene {
            get {
                return ResourceManager.GetString("Tiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string Tipo_activo {
            get {
                return ResourceManager.GetString("Tipo_activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        public static string Tipo_activo_simple {
            get {
                return ResourceManager.GetString("Tipo_activo_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The category {0} has not been created..
        /// </summary>
        public static string Tipo_creado_error {
            get {
                return ResourceManager.GetString("Tipo_creado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The category {0} has been successfully created..
        /// </summary>
        public static string Tipo_creado_exito {
            get {
                return ResourceManager.GetString("Tipo_creado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The category {0} has not been edited..
        /// </summary>
        public static string Tipo_editado_error {
            get {
                return ResourceManager.GetString("Tipo_editado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The category {0} has been successfully edited..
        /// </summary>
        public static string Tipo_editado_exito {
            get {
                return ResourceManager.GetString("Tipo_editado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The category {0} has not been deleted..
        /// </summary>
        public static string Tipo_eliminado_error {
            get {
                return ResourceManager.GetString("Tipo_eliminado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The category {0} has been successfully deleted..
        /// </summary>
        public static string Tipo_eliminado_exito {
            get {
                return ResourceManager.GetString("Tipo_eliminado_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products per page.
        /// </summary>
        public static string Tipos_pagina {
            get {
                return ResourceManager.GetString("Tipos_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Product.
        /// </summary>
        public static string Titulo_crear {
            get {
                return ResourceManager.GetString("Titulo_crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Product.
        /// </summary>
        public static string Titulo_editar {
            get {
                return ResourceManager.GetString("Titulo_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Product.
        /// </summary>
        public static string Titulo_eliminar {
            get {
                return ResourceManager.GetString("Titulo_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total assets.
        /// </summary>
        public static string Total_activos_empresa {
            get {
                return ResourceManager.GetString("Total_activos_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No products added to the list..
        /// </summary>
        public static string Vacio {
            get {
                return ResourceManager.GetString("Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a value for row.
        /// </summary>
        public static string Valor_requerido {
            get {
                return ResourceManager.GetString("Valor_requerido", resourceCulture);
            }
        }
    }
}
