//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnidadesMedida {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnidadesMedida() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.UnidadesMedida", typeof(UnidadesMedida).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turns/Minute.
        /// </summary>
        public static string Giros_minuto {
            get {
                return ResourceManager.GetString("Giros_minuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours.
        /// </summary>
        public static string Horas {
            get {
                return ResourceManager.GetString("Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilometers.
        /// </summary>
        public static string Kilometros {
            get {
                return ResourceManager.GetString("Kilometros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liters.
        /// </summary>
        public static string Litros {
            get {
                return ResourceManager.GetString("Litros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meters.
        /// </summary>
        public static string Metros {
            get {
                return ResourceManager.GetString("Metros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minutes.
        /// </summary>
        public static string Minutos {
            get {
                return ResourceManager.GetString("Minutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Knots.
        /// </summary>
        public static string Nudos {
            get {
                return ResourceManager.GetString("Nudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seconds.
        /// </summary>
        public static string Segundos {
            get {
                return ResourceManager.GetString("Segundos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volts.
        /// </summary>
        public static string Voltios {
            get {
                return ResourceManager.GetString("Voltios", resourceCulture);
            }
        }
    }
}
