//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Usuarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Usuarios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Usuarios", typeof(Usuarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For the Manager role it is necessary to indicate the company or fleet.
        /// </summary>
        public static string AdminFlota_flota_error {
            get {
                return ResourceManager.GetString("AdminFlota_flota_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your phone number has been added..
        /// </summary>
        public static string Agregado_telefono {
            get {
                return ResourceManager.GetString("Agregado_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Now the user also belongs to the specified roles..
        /// </summary>
        public static string Anadidos_roles_correcto {
            get {
                return ResourceManager.GetString("Anadidos_roles_correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change account settings.
        /// </summary>
        public static string Cambiar_configuracion {
            get {
                return ResourceManager.GetString("Cambiar_configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string Cambiar_pass {
            get {
                return ResourceManager.GetString("Cambiar_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change the current user password.
        /// </summary>
        public static string Cambiar_pass_descripcion {
            get {
                return ResourceManager.GetString("Cambiar_pass_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password form.
        /// </summary>
        public static string Cambiar_pass_info {
            get {
                return ResourceManager.GetString("Cambiar_pass_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click on it for help.
        /// </summary>
        public static string Click_ayuda {
            get {
                return ResourceManager.GetString("Click_ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your security code is: .
        /// </summary>
        public static string Codigo_seguridad_es {
            get {
                return ResourceManager.GetString("Codigo_seguridad_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User {0} registration completed successfully.
        /// </summary>
        public static string Correo_registro_cuerpo {
            get {
                return ResourceManager.GetString("Correo_registro_cuerpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful registration to the {0}.
        /// </summary>
        public static string Correo_registro_titulo {
            get {
                return ResourceManager.GetString("Correo_registro_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create User.
        /// </summary>
        public static string Crear_usuario {
            get {
                return ResourceManager.GetString("Crear_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User {0} has been successfully created..
        /// </summary>
        public static string Crear_usuario_correcto {
            get {
                return ResourceManager.GetString("Crear_usuario_correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creating a new user.
        /// </summary>
        public static string Crear_usuario_descripcion {
            get {
                return ResourceManager.GetString("Crear_usuario_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating user {0}. .
        /// </summary>
        public static string Crear_usuario_error {
            get {
                return ResourceManager.GetString("Crear_usuario_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the new user information below.
        /// </summary>
        public static string Crear_usuario_info {
            get {
                return ResourceManager.GetString("Crear_usuario_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User roles.
        /// </summary>
        public static string Crear_usuario_roles {
            get {
                return ResourceManager.GetString("Crear_usuario_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User detail.
        /// </summary>
        public static string Detalle_usuario {
            get {
                return ResourceManager.GetString("Detalle_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information of an existing user.
        /// </summary>
        public static string Detalle_usuario_descripcion {
            get {
                return ResourceManager.GetString("Detalle_usuario_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information of the selected user is shown below.
        /// </summary>
        public static string Detalle_usuario_info {
            get {
                return ResourceManager.GetString("Detalle_usuario_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For the Distributor role it is necessary to indicate the entity.
        /// </summary>
        public static string Distribuidor_empresa_error {
            get {
                return ResourceManager.GetString("Distribuidor_empresa_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Distributor role can not be assigned because the entity is not a Distributor.
        /// </summary>
        public static string Distribuidor_entidad_error {
            get {
                return ResourceManager.GetString("Distribuidor_entidad_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit User.
        /// </summary>
        public static string Editar_usuario {
            get {
                return ResourceManager.GetString("Editar_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User {0} has been successfully edited..
        /// </summary>
        public static string Editar_usuario_correcto {
            get {
                return ResourceManager.GetString("Editar_usuario_correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifying an existing user.
        /// </summary>
        public static string Editar_usuario_descripcion {
            get {
                return ResourceManager.GetString("Editar_usuario_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error editing user {0}. .
        /// </summary>
        public static string Editar_usuario_error {
            get {
                return ResourceManager.GetString("Editar_usuario_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to change user {0} password. .
        /// </summary>
        public static string Editar_usuario_error_pass {
            get {
                return ResourceManager.GetString("Editar_usuario_error_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error editing user roles {0}. .
        /// </summary>
        public static string Editar_usuario_error_roles {
            get {
                return ResourceManager.GetString("Editar_usuario_error_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit from the user below.
        /// </summary>
        public static string Editar_usuario_info {
            get {
                return ResourceManager.GetString("Editar_usuario_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete User.
        /// </summary>
        public static string Eliminar_usuario {
            get {
                return ResourceManager.GetString("Eliminar_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User {0} has been successfully deleted.
        /// </summary>
        public static string Eliminar_usuario_correcto {
            get {
                return ResourceManager.GetString("Eliminar_usuario_correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting an existing user.
        /// </summary>
        public static string Eliminar_usuario_descripcion {
            get {
                return ResourceManager.GetString("Eliminar_usuario_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while deleting user {0}. .
        /// </summary>
        public static string Eliminar_usuario_error {
            get {
                return ResourceManager.GetString("Eliminar_usuario_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected user?.
        /// </summary>
        public static string Eliminar_usuario_info {
            get {
                return ResourceManager.GetString("Eliminar_usuario_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t unblock the user {0} because the entity to which it belongs is blocked..
        /// </summary>
        public static string Entidad_bloqueada {
            get {
                return ResourceManager.GetString("Entidad_bloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has occurred..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error in assigning roles to user {0}. .
        /// </summary>
        public static string Error_asignar_roles {
            get {
                return ResourceManager.GetString("Error_asignar_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image does not match the minimum dimensions required ({0}). Please try again with another image..
        /// </summary>
        public static string Error_dimensiones {
            get {
                return ResourceManager.GetString("Error_dimensiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is not allowed to delete the only Super Administrator of the application..
        /// </summary>
        public static string Error_eliminar {
            get {
                return ResourceManager.GetString("Error_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not manage users of role {0}.
        /// </summary>
        public static string Error_permisos_rol {
            get {
                return ResourceManager.GetString("Error_permisos_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The confirmation password and password do not match..
        /// </summary>
        public static string Error_repita_password {
            get {
                return ResourceManager.GetString("Error_repita_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password and confirmation password do not match..
        /// </summary>
        public static string Error_repita_password_nueva {
            get {
                return ResourceManager.GetString("Error_repita_password_nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user&apos;s image must be of type {0}.
        /// </summary>
        public static string Error_tipo_fichero {
            get {
                return ResourceManager.GetString("Error_tipo_fichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not check phone.
        /// </summary>
        public static string No_comproba_telefono {
            get {
                return ResourceManager.GetString("No_comproba_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name and Surname.
        /// </summary>
        public static string Nombre_completo {
            get {
                return ResourceManager.GetString("Nombre_completo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New User.
        /// </summary>
        public static string Nuevo_usuario {
            get {
                return ResourceManager.GetString("Nuevo_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users count.
        /// </summary>
        public static string Numero_usuarios {
            get {
                return ResourceManager.GetString("Numero_usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string Password_actual {
            get {
                return ResourceManager.GetString("Password_actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been changed..
        /// </summary>
        public static string Password_cambiada {
            get {
                return ResourceManager.GetString("Password_cambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been set..
        /// </summary>
        public static string Password_establecida {
            get {
                return ResourceManager.GetString("Password_establecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string Password_nueva {
            get {
                return ResourceManager.GetString("Password_nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat new password.
        /// </summary>
        public static string Password_nueva_confirmar {
            get {
                return ResourceManager.GetString("Password_nueva_confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My profile.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifying my profile.
        /// </summary>
        public static string Perfil_descripcion {
            get {
                return ResourceManager.GetString("Perfil_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User profile has been successfully edited..
        /// </summary>
        public static string Perfil_usuario_correcto {
            get {
                return ResourceManager.GetString("Perfil_usuario_correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error editing profile..
        /// </summary>
        public static string Perfil_usuario_error {
            get {
                return ResourceManager.GetString("Perfil_usuario_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify your profile data.
        /// </summary>
        public static string Perfil_usuario_info {
            get {
                return ResourceManager.GetString("Perfil_usuario_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your two-factor authentication provider has been established..
        /// </summary>
        public static string Proveedor_establecido {
            get {
                return ResourceManager.GetString("Proveedor_establecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your phone number has been removed..
        /// </summary>
        public static string Quitado_telefono {
            get {
                return ResourceManager.GetString("Quitado_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember account?.
        /// </summary>
        public static string Recordar_cuenta {
            get {
                return ResourceManager.GetString("Recordar_cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember browser?.
        /// </summary>
        public static string Recordar_explorador {
            get {
                return ResourceManager.GetString("Recordar_explorador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat password.
        /// </summary>
        public static string Repita_password {
            get {
                return ResourceManager.GetString("Repita_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The dimensions of the image must be at least {0} and not exceed {1}..
        /// </summary>
        public static string Requisitos_imagen {
            get {
                return ResourceManager.GetString("Requisitos_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name and surname of the user.
        /// </summary>
        public static string Title_Nombre_Completo {
            get {
                return ResourceManager.GetString("Title_Nombre_Completo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application access name of the user.
        /// </summary>
        public static string Title_Nombre_Usuario {
            get {
                return ResourceManager.GetString("Title_Nombre_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string Usuario_ {
            get {
                return ResourceManager.GetString("Usuario_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user {0} has not been locked..
        /// </summary>
        public static string Usuario_bloqueado_error {
            get {
                return ResourceManager.GetString("Usuario_bloqueado_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For the User role it is necessary to indicate the company or fleet.
        /// </summary>
        public static string Usuario_flota_error {
            get {
                return ResourceManager.GetString("Usuario_flota_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not create an user without associated modules..
        /// </summary>
        public static string Usuario_no_modulos {
            get {
                return ResourceManager.GetString("Usuario_no_modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not edit an user without associated modules..
        /// </summary>
        public static string Usuario_no_modulos_editar {
            get {
                return ResourceManager.GetString("Usuario_no_modulos_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existing users in the system.
        /// </summary>
        public static string Usuarios_descripcion {
            get {
                return ResourceManager.GetString("Usuarios_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users per page:.
        /// </summary>
        public static string Usuarios_pagina {
            get {
                return ResourceManager.GetString("Usuarios_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telematics Users.
        /// </summary>
        public static string Usuarios_telematica {
            get {
                return ResourceManager.GetString("Usuarios_telematica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trace Users.
        /// </summary>
        public static string Usuarios_trace {
            get {
                return ResourceManager.GetString("Usuarios_trace", resourceCulture);
            }
        }
    }
}
