//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Verticales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Verticales() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("traducciones.Verticales", typeof(Verticales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asset per product.
        /// </summary>
        public static string Activo_por_producto {
            get {
                return ResourceManager.GetString("Activo_por_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One asset per product.
        /// </summary>
        public static string Activo_producto {
            get {
                return ResourceManager.GetString("Activo_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is required..
        /// </summary>
        public static string Campo_vacio {
            get {
                return ResourceManager.GetString("Campo_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New vertical.
        /// </summary>
        public static string Crear_vertical {
            get {
                return ResourceManager.GetString("Crear_vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete an existing vertical.
        /// </summary>
        public static string Descripcion_borrado {
            get {
                return ResourceManager.GetString("Descripcion_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new vertical.
        /// </summary>
        public static string Descripcion_creacion {
            get {
                return ResourceManager.GetString("Descripcion_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about an existing vertical.
        /// </summary>
        public static string Descripcion_detalles {
            get {
                return ResourceManager.GetString("Descripcion_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verticals stored in system.
        /// </summary>
        public static string Descripcion_index {
            get {
                return ResourceManager.GetString("Descripcion_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit vertical.
        /// </summary>
        public static string Editar_vertical {
            get {
                return ResourceManager.GetString("Editar_vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete vertical.
        /// </summary>
        public static string Eliminar_vertical {
            get {
                return ResourceManager.GetString("Eliminar_vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the information for the selected vertical?.
        /// </summary>
        public static string Encabezado_borrado {
            get {
                return ResourceManager.GetString("Encabezado_borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information for the new vertical below.
        /// </summary>
        public static string Encabezado_creacion {
            get {
                return ResourceManager.GetString("Encabezado_creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information for the selected vertical is shown below.
        /// </summary>
        public static string Encabezado_detalles {
            get {
                return ResourceManager.GetString("Encabezado_detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the information you want to edit in the vertical below.
        /// </summary>
        public static string Encabezado_edicion {
            get {
                return ResourceManager.GetString("Encabezado_edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select at least one module.
        /// </summary>
        public static string Error_sin_modulos {
            get {
                return ResourceManager.GetString("Error_sin_modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The vertical {0} is associated to 1 or more entities. You can not remove it..
        /// </summary>
        public static string Error_vertical_entidades {
            get {
                return ResourceManager.GetString("Error_vertical_entidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modules.
        /// </summary>
        public static string Lista_modulos {
            get {
                return ResourceManager.GetString("Lista_modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vertical.
        /// </summary>
        public static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The vertical {0} has not been created..
        /// </summary>
        public static string Vertical_creada_error {
            get {
                return ResourceManager.GetString("Vertical_creada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The vertical {0} has been successfuly created..
        /// </summary>
        public static string Vertical_creada_exito {
            get {
                return ResourceManager.GetString("Vertical_creada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The vertical {0} has not been edited..
        /// </summary>
        public static string Vertical_editada_error {
            get {
                return ResourceManager.GetString("Vertical_editada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The vertical {0} has been successfuly edited..
        /// </summary>
        public static string Vertical_editada_exito {
            get {
                return ResourceManager.GetString("Vertical_editada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The vertical {0} has not been deleted..
        /// </summary>
        public static string Vertical_eliminada_error {
            get {
                return ResourceManager.GetString("Vertical_eliminada_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The vertical {0} has been succesfully deleted..
        /// </summary>
        public static string Vertical_eliminada_exito {
            get {
                return ResourceManager.GetString("Vertical_eliminada_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verticals.
        /// </summary>
        public static string Vertical_plural {
            get {
                return ResourceManager.GetString("Vertical_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verticals per page:.
        /// </summary>
        public static string Verticales_pagina {
            get {
                return ResourceManager.GetString("Verticales_pagina", resourceCulture);
            }
        }
    }
}
